### ISSUE TITLE
Installation failed using pip

### ISSUE THREAD

**Issue by jalanb** [scopatz/xonsh#1]
```shell
$ pip3 install xonsh
Collecting xonsh
  Downloading xonsh-0.1.0.tar.gz (70kB)
    100% |################################| 73kB 747kB/s 
                               \u2553\u2588\u2588\u2584
                              \u2559\u2588\u2588\u2580\u2588\u2588\u2555
                             \u2590\u2588\u25884\u03a6\u2588\u2580\u2588\u258c
                           ²\u2588\u2588\u2584\u2588\u2588\u2588\u2580\u2588\u2588^\u2588\u2588
                         -\u2588\u2588\u2588\u2569\u2580 " \u2552\u2584\u2588\u2588\u2588\u2588\u2588\u2580\u2588
                          \u2551\u2588\u2588\u2580\u2580W\u2564\u2584\u2580 \u2590\u2551\u2588\u2558 \u255d\u2588
                     \u2584m\u2580%\u03a6\u2580\u2580  \u255d*"    ,\u03b1\u2588\u2588\u2588\u2588\u2588\u2593\u2584,\u2584\u2580\u0393"\u2580\u2555
                     "\u2580\u2588\u2588¼"     \u2584\u2550\u2566\u2588\u255f\u2551\u2588\u2580 \u2553 `^`   ,\u2584 \u2562\u2555
                      ,\u2580\u256bM\u2588\u2590j\u2553\u255f\u2580 \u2554\u2593\u2584\u2588\u2580  '\u2551 \u2554    \u2563\u2551\u258c  \u2580\u2584
                   \u2584m\u2580\u2580\u2588\u2588\u2588\u256c\u2588\u255d\u2580  \u2588\u2580^      "ÜM  j\u2590\u255f\u256b\u2568\u2592   \u2559\u2580\u2261\u2550\u2564\u2550m\u2580\u2557
                   \u2588æsæ\u2553  \u2555, ,\u2584Ä   \u2590'\u2555H   LU  \u2551\u2551\u2560\u256bÅ^2=\u2310         \u2588
                \u2584æ%Å\u2588\u2588\u2588\u2560\u2588ª\u2559\u2584\u2588\u2580      $1\u2559       \u2551\u2551\u255f\u256b\u2569*T\u2584           \u258c
               \u2559\u2557%\u2584,\u2566\u2588\u2588\u258c\u2588\u258c\u2588\u2562M         \u2555      M\u2551\u2551\u2551\u2551\u2588\u2550\u2310\u207f"^         \u256b
                 \u2559\u2563\u2580\u2588\u2588\u2588\u2588@\u2588\u2591\u2588    \u258c\u2555\u2555   `      \u258c\u2551\u2590\u2590\u2551\u2588D\u2550\u2248\u2310¬\u207f      s \u2551\u2310
                   \u2559\u256c\u2588\u2588\u2588\u2593\u2551\u2588`     \u258c\u255a     \u2555   \u2555\u258c\u2551\u2590\u2590\u2563\u258c\u2310*\u2592\u2592Dù`       \u2590\u258c
                    \u2559\u256c\u2588\u2588\u2568U\u2588      \u255f      $ \u258c \u258c\u258c\u2590\u2590\u2590M\u2588\u2584\u2550\u2264\u2310%       \u2553\u2310 \u258c
                     \u2551\u2551\u2588\u2584\u258c\u2551             \u255f \u258c \u258cM\u2590\u2590\u2590M\u2588\u2580\u2592\u2592\u259222,       \u2590\u258c
                      \u2588\u2588\u2588\u2559^\u258c            \u2551 \u258c \u2310M\u2590\u2590\u2590M\u2588\u2264\u2310\u2310¬\u2500\u2500        \u2590M
                      \u2551\u2588\u2588 \u258c\u2559   \u2553       H\u2551 \u258c\u2552 M\u2551\u2590\u2590M\u2588"^^^^^"\u207f      \u2551
                       \u2588\u2588\u2555\u2559@\u2593   \u2555      \u258c\u2551 H'  \u2551\u2590\u2590\u2590\u2588\u2550\u2550=.,,,       \u2588
                       \u2559\u2588\u2593\u2554\u255a\u255a\u2588     \u2560   \u258c\u2514\u2552 \u258c\u2590 \u255a\u2551\u2551\u2551\u2580****\u207f -      \u2553\u258c
                        \u2559\u2588\u258c¼V\u255a\u258c   \u258c  \u2555 \u258c \u2551\u2552 \u2551 \u258c\u2592\u2560\u2588\u2580\u2264\u2264\u2264\u2264\u2264\u2310       \u2588
                         \u2559\u2588\u258c\u2554\u2588\u255a\u258c     \u2518 M \u258c\u2551 \u256b UUM\u2588\u2588J^^"        \u2590\u258c
                          \u2559\u2588\u2588\u2559\u2588\u2559\u258c  \u2555$j  \u2590\u2310\u258c \u258c\u2551\u255d\u255f\u2588Å%%%\u2248\u2550        \u2588
                           \u2559\u2563\u2588\u2563\u2588^\u258c \u2560\u2551\u2590  \u2551 \u258c\u2590.DU\u2588\u2588^[""\u207f       -\u2552\u258c
                             \u2580\u2588\u2584\u2588`\u258c \u2591M\u2580 \u258c\u2590 Å£\u255d\u255d\u2588\u255c%\u2248\u2550\u2553""w   \u207f\u2310 \u2588
                              `\u2580\u2584\u2580`\u258c \u258c\u2588\u2590\u2310\u2551\u2590UW\u2556\u2588\u2588%\u2264\u2550\u2591*\u2500    =z \u2584\u0393
                                \u2559\u2588\u2588\u2559\u2584\u258c\u2588  \u258cÅ\u255b\u2563\u2588\u2588\u2568%\u2564\u0192\u207f=    -` \u2584\u2518
                                  \u2588\u258c\u2562\u2593\u258c\u258c W £6\u2588\u2564,"\u207f `   \u2584\u2261\u2580\u2580\u2580
                                   \u2588"\u2588\u258c\u258c\u255fÅ\u2553\u2588\u2553\u2588\u2580%`    \u2584\u2580
                                   \u2559\u258c\u2588\u2588`\u2592U\u2593U\u2588%\u2557*     \u2588
                                    \u258c\u256b\u2551 \u258cÅÅ\u2551\u2580\u255b¬`      `"\u2588
                                    \u258c\u256b  \u256b\u255f \u2588\u2584     ~\u2566%\u2592\u25654^
                                    \u258c\u258c  "M\u2588 `\u2580\u2555 X\u2555"\u2557\u2584\u2580^
                                    \u2588\u258c   \u2553M   \u2559\u2580e\u2580\u2580^
                                    \u2559\u2588\u2588\u2584\u2584\u2580
                                      ^^
    Remove xonsh/lexer_table.py
    Remove xonsh/parser_table.py
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 95, in <module>
        main()
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 34, in main
        build_tables()
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 26, in build_tables
        from xonsh.parser import Parser
      File "/tmp/pip-build-tr2gsevu/xonsh/xonsh/parser.py", line 7, in <module>
        from ply import yacc
    ImportError: No module named 'ply'
    Complete output from command python setup.py egg_info:
    
    
                               \u2553\u2588\u2588\u2584
    
                              \u2559\u2588\u2588\u2580\u2588\u2588\u2555
    
                             \u2590\u2588\u25884\u03a6\u2588\u2580\u2588\u258c
    
                           ²\u2588\u2588\u2584\u2588\u2588\u2588\u2580\u2588\u2588^\u2588\u2588
    
                         -\u2588\u2588\u2588\u2569\u2580 " \u2552\u2584\u2588\u2588\u2588\u2588\u2588\u2580\u2588
    
                          \u2551\u2588\u2588\u2580\u2580W\u2564\u2584\u2580 \u2590\u2551\u2588\u2558 \u255d\u2588
    
                     \u2584m\u2580%\u03a6\u2580\u2580  \u255d*"    ,\u03b1\u2588\u2588\u2588\u2588\u2588\u2593\u2584,\u2584\u2580\u0393"\u2580\u2555
    
                     "\u2580\u2588\u2588¼"     \u2584\u2550\u2566\u2588\u255f\u2551\u2588\u2580 \u2553 `^`   ,\u2584 \u2562\u2555
    
                      ,\u2580\u256bM\u2588\u2590j\u2553\u255f\u2580 \u2554\u2593\u2584\u2588\u2580  '\u2551 \u2554    \u2563\u2551\u258c  \u2580\u2584
    
                   \u2584m\u2580\u2580\u2588\u2588\u2588\u256c\u2588\u255d\u2580  \u2588\u2580^      "ÜM  j\u2590\u255f\u256b\u2568\u2592   \u2559\u2580\u2261\u2550\u2564\u2550m\u2580\u2557
    
                   \u2588æsæ\u2553  \u2555, ,\u2584Ä   \u2590'\u2555H   LU  \u2551\u2551\u2560\u256bÅ^2=\u2310         \u2588
    
                \u2584æ%Å\u2588\u2588\u2588\u2560\u2588ª\u2559\u2584\u2588\u2580      $1\u2559       \u2551\u2551\u255f\u256b\u2569*T\u2584           \u258c
    
               \u2559\u2557%\u2584,\u2566\u2588\u2588\u258c\u2588\u258c\u2588\u2562M         \u2555      M\u2551\u2551\u2551\u2551\u2588\u2550\u2310\u207f"^         \u256b
    
                 \u2559\u2563\u2580\u2588\u2588\u2588\u2588@\u2588\u2591\u2588    \u258c\u2555\u2555   `      \u258c\u2551\u2590\u2590\u2551\u2588D\u2550\u2248\u2310¬\u207f      s \u2551\u2310
    
                   \u2559\u256c\u2588\u2588\u2588\u2593\u2551\u2588`     \u258c\u255a     \u2555   \u2555\u258c\u2551\u2590\u2590\u2563\u258c\u2310*\u2592\u2592Dù`       \u2590\u258c
    
                    \u2559\u256c\u2588\u2588\u2568U\u2588      \u255f      $ \u258c \u258c\u258c\u2590\u2590\u2590M\u2588\u2584\u2550\u2264\u2310%       \u2553\u2310 \u258c
    
                     \u2551\u2551\u2588\u2584\u258c\u2551             \u255f \u258c \u258cM\u2590\u2590\u2590M\u2588\u2580\u2592\u2592\u259222,       \u2590\u258c
    
                      \u2588\u2588\u2588\u2559^\u258c            \u2551 \u258c \u2310M\u2590\u2590\u2590M\u2588\u2264\u2310\u2310¬\u2500\u2500        \u2590M
    
                      \u2551\u2588\u2588 \u258c\u2559   \u2553       H\u2551 \u258c\u2552 M\u2551\u2590\u2590M\u2588"^^^^^"\u207f      \u2551
    
                       \u2588\u2588\u2555\u2559@\u2593   \u2555      \u258c\u2551 H'  \u2551\u2590\u2590\u2590\u2588\u2550\u2550=.,,,       \u2588
    
                       \u2559\u2588\u2593\u2554\u255a\u255a\u2588     \u2560   \u258c\u2514\u2552 \u258c\u2590 \u255a\u2551\u2551\u2551\u2580****\u207f -      \u2553\u258c
    
                        \u2559\u2588\u258c¼V\u255a\u258c   \u258c  \u2555 \u258c \u2551\u2552 \u2551 \u258c\u2592\u2560\u2588\u2580\u2264\u2264\u2264\u2264\u2264\u2310       \u2588
    
                         \u2559\u2588\u258c\u2554\u2588\u255a\u258c     \u2518 M \u258c\u2551 \u256b UUM\u2588\u2588J^^"        \u2590\u258c
    
                          \u2559\u2588\u2588\u2559\u2588\u2559\u258c  \u2555$j  \u2590\u2310\u258c \u258c\u2551\u255d\u255f\u2588Å%%%\u2248\u2550        \u2588
    
                           \u2559\u2563\u2588\u2563\u2588^\u258c \u2560\u2551\u2590  \u2551 \u258c\u2590.DU\u2588\u2588^[""\u207f       -\u2552\u258c
    
                             \u2580\u2588\u2584\u2588`\u258c \u2591M\u2580 \u258c\u2590 Å£\u255d\u255d\u2588\u255c%\u2248\u2550\u2553""w   \u207f\u2310 \u2588
    
                              `\u2580\u2584\u2580`\u258c \u258c\u2588\u2590\u2310\u2551\u2590UW\u2556\u2588\u2588%\u2264\u2550\u2591*\u2500    =z \u2584\u0393
    
                                \u2559\u2588\u2588\u2559\u2584\u258c\u2588  \u258cÅ\u255b\u2563\u2588\u2588\u2568%\u2564\u0192\u207f=    -` \u2584\u2518
    
                                  \u2588\u258c\u2562\u2593\u258c\u258c W £6\u2588\u2564,"\u207f `   \u2584\u2261\u2580\u2580\u2580
    
                                   \u2588"\u2588\u258c\u258c\u255fÅ\u2553\u2588\u2553\u2588\u2580%`    \u2584\u2580
    
                                   \u2559\u258c\u2588\u2588`\u2592U\u2593U\u2588%\u2557*     \u2588
    
                                    \u258c\u256b\u2551 \u258cÅÅ\u2551\u2580\u255b¬`      `"\u2588
    
                                    \u258c\u256b  \u256b\u255f \u2588\u2584     ~\u2566%\u2592\u25654^
    
                                    \u258c\u258c  "M\u2588 `\u2580\u2555 X\u2555"\u2557\u2584\u2580^
    
                                    \u2588\u258c   \u2553M   \u2559\u2580e\u2580\u2580^
    
                                    \u2559\u2588\u2588\u2584\u2584\u2580
    
                                      ^^
    
    
    
    Remove xonsh/lexer_table.py
    
    Remove xonsh/parser_table.py
    
    Building lexer and parser tables.
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 95, in <module>
    
        main()
    
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 34, in main
    
        build_tables()
    
      File "/tmp/pip-build-tr2gsevu/xonsh/setup.py", line 26, in build_tables
    
        from xonsh.parser import Parser
    
      File "/tmp/pip-build-tr2gsevu/xonsh/xonsh/parser.py", line 7, in <module>
    
        from ply import yacc
    
    ImportError: No module named 'ply'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tr2gsevu/xonsh

2015-03-09 09:04:51 [alanb@moon:~] [2.7.5] 4s 1 $ 
$ pip3 install ply
Collecting ply
  Downloading ply-3.4.tar.gz (138kB)
    100% |################################| 139kB 716kB/s 
Installing collected packages: ply
  Running setup.py install for ply
Successfully installed ply-3.4

2015-03-09 09:05:04 [alanb@moon:~] [2.7.5] 13s $ 
$ pip3 install xonsh
Collecting xonsh
  Using cached xonsh-0.1.0.tar.gz
                               \u2553\u2588\u2588\u2584
                              \u2559\u2588\u2588\u2580\u2588\u2588\u2555
                             \u2590\u2588\u25884\u03a6\u2588\u2580\u2588\u258c
                           ²\u2588\u2588\u2584\u2588\u2588\u2588\u2580\u2588\u2588^\u2588\u2588
                         -\u2588\u2588\u2588\u2569\u2580 " \u2552\u2584\u2588\u2588\u2588\u2588\u2588\u2580\u2588
                          \u2551\u2588\u2588\u2580\u2580W\u2564\u2584\u2580 \u2590\u2551\u2588\u2558 \u255d\u2588
                     \u2584m\u2580%\u03a6\u2580\u2580  \u255d*"    ,\u03b1\u2588\u2588\u2588\u2588\u2588\u2593\u2584,\u2584\u2580\u0393"\u2580\u2555
                     "\u2580\u2588\u2588¼"     \u2584\u2550\u2566\u2588\u255f\u2551\u2588\u2580 \u2553 `^`   ,\u2584 \u2562\u2555
                      ,\u2580\u256bM\u2588\u2590j\u2553\u255f\u2580 \u2554\u2593\u2584\u2588\u2580  '\u2551 \u2554    \u2563\u2551\u258c  \u2580\u2584
                   \u2584m\u2580\u2580\u2588\u2588\u2588\u256c\u2588\u255d\u2580  \u2588\u2580^      "ÜM  j\u2590\u255f\u256b\u2568\u2592   \u2559\u2580\u2261\u2550\u2564\u2550m\u2580\u2557
                   \u2588æsæ\u2553  \u2555, ,\u2584Ä   \u2590'\u2555H   LU  \u2551\u2551\u2560\u256bÅ^2=\u2310         \u2588
                \u2584æ%Å\u2588\u2588\u2588\u2560\u2588ª\u2559\u2584\u2588\u2580      $1\u2559       \u2551\u2551\u255f\u256b\u2569*T\u2584           \u258c
               \u2559\u2557%\u2584,\u2566\u2588\u2588\u258c\u2588\u258c\u2588\u2562M         \u2555      M\u2551\u2551\u2551\u2551\u2588\u2550\u2310\u207f"^         \u256b
                 \u2559\u2563\u2580\u2588\u2588\u2588\u2588@\u2588\u2591\u2588    \u258c\u2555\u2555   `      \u258c\u2551\u2590\u2590\u2551\u2588D\u2550\u2248\u2310¬\u207f      s \u2551\u2310
                   \u2559\u256c\u2588\u2588\u2588\u2593\u2551\u2588`     \u258c\u255a     \u2555   \u2555\u258c\u2551\u2590\u2590\u2563\u258c\u2310*\u2592\u2592Dù`       \u2590\u258c
                    \u2559\u256c\u2588\u2588\u2568U\u2588      \u255f      $ \u258c \u258c\u258c\u2590\u2590\u2590M\u2588\u2584\u2550\u2264\u2310%       \u2553\u2310 \u258c
                     \u2551\u2551\u2588\u2584\u258c\u2551             \u255f \u258c \u258cM\u2590\u2590\u2590M\u2588\u2580\u2592\u2592\u259222,       \u2590\u258c
                      \u2588\u2588\u2588\u2559^\u258c            \u2551 \u258c \u2310M\u2590\u2590\u2590M\u2588\u2264\u2310\u2310¬\u2500\u2500        \u2590M
                      \u2551\u2588\u2588 \u258c\u2559   \u2553       H\u2551 \u258c\u2552 M\u2551\u2590\u2590M\u2588"^^^^^"\u207f      \u2551
                       \u2588\u2588\u2555\u2559@\u2593   \u2555      \u258c\u2551 H'  \u2551\u2590\u2590\u2590\u2588\u2550\u2550=.,,,       \u2588
                       \u2559\u2588\u2593\u2554\u255a\u255a\u2588     \u2560   \u258c\u2514\u2552 \u258c\u2590 \u255a\u2551\u2551\u2551\u2580****\u207f -      \u2553\u258c
                        \u2559\u2588\u258c¼V\u255a\u258c   \u258c  \u2555 \u258c \u2551\u2552 \u2551 \u258c\u2592\u2560\u2588\u2580\u2264\u2264\u2264\u2264\u2264\u2310       \u2588
                         \u2559\u2588\u258c\u2554\u2588\u255a\u258c     \u2518 M \u258c\u2551 \u256b UUM\u2588\u2588J^^"        \u2590\u258c
                          \u2559\u2588\u2588\u2559\u2588\u2559\u258c  \u2555$j  \u2590\u2310\u258c \u258c\u2551\u255d\u255f\u2588Å%%%\u2248\u2550        \u2588
                           \u2559\u2563\u2588\u2563\u2588^\u258c \u2560\u2551\u2590  \u2551 \u258c\u2590.DU\u2588\u2588^[""\u207f       -\u2552\u258c
                             \u2580\u2588\u2584\u2588`\u258c \u2591M\u2580 \u258c\u2590 Å£\u255d\u255d\u2588\u255c%\u2248\u2550\u2553""w   \u207f\u2310 \u2588
                              `\u2580\u2584\u2580`\u258c \u258c\u2588\u2590\u2310\u2551\u2590UW\u2556\u2588\u2588%\u2264\u2550\u2591*\u2500    =z \u2584\u0393
                                \u2559\u2588\u2588\u2559\u2584\u258c\u2588  \u258cÅ\u255b\u2563\u2588\u2588\u2568%\u2564\u0192\u207f=    -` \u2584\u2518
                                  \u2588\u258c\u2562\u2593\u258c\u258c W £6\u2588\u2564,"\u207f `   \u2584\u2261\u2580\u2580\u2580
                                   \u2588"\u2588\u258c\u258c\u255fÅ\u2553\u2588\u2553\u2588\u2580%`    \u2584\u2580
                                   \u2559\u258c\u2588\u2588`\u2592U\u2593U\u2588%\u2557*     \u2588
                                    \u258c\u256b\u2551 \u258cÅÅ\u2551\u2580\u255b¬`      `"\u2588
                                    \u258c\u256b  \u256b\u255f \u2588\u2584     ~\u2566%\u2592\u25654^
                                    \u258c\u258c  "M\u2588 `\u2580\u2555 X\u2555"\u2557\u2584\u2580^
                                    \u2588\u258c   \u2553M   \u2559\u2580e\u2580\u2580^
                                    \u2559\u2588\u2588\u2584\u2584\u2580
                                      ^^
    Remove xonsh/lexer_table.py
    Remove xonsh/parser_table.py
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-z0uet8y1/xonsh/setup.py", line 95, in <module>
        main()
      File "/tmp/pip-build-z0uet8y1/xonsh/setup.py", line 35, in main
        with open('readme.rst', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'
    Complete output from command python setup.py egg_info:
    
    
                               \u2553\u2588\u2588\u2584
    
                              \u2559\u2588\u2588\u2580\u2588\u2588\u2555
    
                             \u2590\u2588\u25884\u03a6\u2588\u2580\u2588\u258c
    
                           ²\u2588\u2588\u2584\u2588\u2588\u2588\u2580\u2588\u2588^\u2588\u2588
    
                         -\u2588\u2588\u2588\u2569\u2580 " \u2552\u2584\u2588\u2588\u2588\u2588\u2588\u2580\u2588
    
                          \u2551\u2588\u2588\u2580\u2580W\u2564\u2584\u2580 \u2590\u2551\u2588\u2558 \u255d\u2588
    
                     \u2584m\u2580%\u03a6\u2580\u2580  \u255d*"    ,\u03b1\u2588\u2588\u2588\u2588\u2588\u2593\u2584,\u2584\u2580\u0393"\u2580\u2555
    
                     "\u2580\u2588\u2588¼"     \u2584\u2550\u2566\u2588\u255f\u2551\u2588\u2580 \u2553 `^`   ,\u2584 \u2562\u2555
    
                      ,\u2580\u256bM\u2588\u2590j\u2553\u255f\u2580 \u2554\u2593\u2584\u2588\u2580  '\u2551 \u2554    \u2563\u2551\u258c  \u2580\u2584
    
                   \u2584m\u2580\u2580\u2588\u2588\u2588\u256c\u2588\u255d\u2580  \u2588\u2580^      "ÜM  j\u2590\u255f\u256b\u2568\u2592   \u2559\u2580\u2261\u2550\u2564\u2550m\u2580\u2557
    
                   \u2588æsæ\u2553  \u2555, ,\u2584Ä   \u2590'\u2555H   LU  \u2551\u2551\u2560\u256bÅ^2=\u2310         \u2588
    
                \u2584æ%Å\u2588\u2588\u2588\u2560\u2588ª\u2559\u2584\u2588\u2580      $1\u2559       \u2551\u2551\u255f\u256b\u2569*T\u2584           \u258c
    
               \u2559\u2557%\u2584,\u2566\u2588\u2588\u258c\u2588\u258c\u2588\u2562M         \u2555      M\u2551\u2551\u2551\u2551\u2588\u2550\u2310\u207f"^         \u256b
    
                 \u2559\u2563\u2580\u2588\u2588\u2588\u2588@\u2588\u2591\u2588    \u258c\u2555\u2555   `      \u258c\u2551\u2590\u2590\u2551\u2588D\u2550\u2248\u2310¬\u207f      s \u2551\u2310
    
                   \u2559\u256c\u2588\u2588\u2588\u2593\u2551\u2588`     \u258c\u255a     \u2555   \u2555\u258c\u2551\u2590\u2590\u2563\u258c\u2310*\u2592\u2592Dù`       \u2590\u258c
    
                    \u2559\u256c\u2588\u2588\u2568U\u2588      \u255f      $ \u258c \u258c\u258c\u2590\u2590\u2590M\u2588\u2584\u2550\u2264\u2310%       \u2553\u2310 \u258c
    
                     \u2551\u2551\u2588\u2584\u258c\u2551             \u255f \u258c \u258cM\u2590\u2590\u2590M\u2588\u2580\u2592\u2592\u259222,       \u2590\u258c
    
                      \u2588\u2588\u2588\u2559^\u258c            \u2551 \u258c \u2310M\u2590\u2590\u2590M\u2588\u2264\u2310\u2310¬\u2500\u2500        \u2590M
    
                      \u2551\u2588\u2588 \u258c\u2559   \u2553       H\u2551 \u258c\u2552 M\u2551\u2590\u2590M\u2588"^^^^^"\u207f      \u2551
    
                       \u2588\u2588\u2555\u2559@\u2593   \u2555      \u258c\u2551 H'  \u2551\u2590\u2590\u2590\u2588\u2550\u2550=.,,,       \u2588
    
                       \u2559\u2588\u2593\u2554\u255a\u255a\u2588     \u2560   \u258c\u2514\u2552 \u258c\u2590 \u255a\u2551\u2551\u2551\u2580****\u207f -      \u2553\u258c
    
                        \u2559\u2588\u258c¼V\u255a\u258c   \u258c  \u2555 \u258c \u2551\u2552 \u2551 \u258c\u2592\u2560\u2588\u2580\u2264\u2264\u2264\u2264\u2264\u2310       \u2588
    
                         \u2559\u2588\u258c\u2554\u2588\u255a\u258c     \u2518 M \u258c\u2551 \u256b UUM\u2588\u2588J^^"        \u2590\u258c
    
                          \u2559\u2588\u2588\u2559\u2588\u2559\u258c  \u2555$j  \u2590\u2310\u258c \u258c\u2551\u255d\u255f\u2588Å%%%\u2248\u2550        \u2588
    
                           \u2559\u2563\u2588\u2563\u2588^\u258c \u2560\u2551\u2590  \u2551 \u258c\u2590.DU\u2588\u2588^[""\u207f       -\u2552\u258c
    
                             \u2580\u2588\u2584\u2588`\u258c \u2591M\u2580 \u258c\u2590 Å£\u255d\u255d\u2588\u255c%\u2248\u2550\u2553""w   \u207f\u2310 \u2588
    
                              `\u2580\u2584\u2580`\u258c \u258c\u2588\u2590\u2310\u2551\u2590UW\u2556\u2588\u2588%\u2264\u2550\u2591*\u2500    =z \u2584\u0393
    
                                \u2559\u2588\u2588\u2559\u2584\u258c\u2588  \u258cÅ\u255b\u2563\u2588\u2588\u2568%\u2564\u0192\u207f=    -` \u2584\u2518
    
                                  \u2588\u258c\u2562\u2593\u258c\u258c W £6\u2588\u2564,"\u207f `   \u2584\u2261\u2580\u2580\u2580
    
                                   \u2588"\u2588\u258c\u258c\u255fÅ\u2553\u2588\u2553\u2588\u2580%`    \u2584\u2580
    
                                   \u2559\u258c\u2588\u2588`\u2592U\u2593U\u2588%\u2557*     \u2588
    
                                    \u258c\u256b\u2551 \u258cÅÅ\u2551\u2580\u255b¬`      `"\u2588
    
                                    \u258c\u256b  \u256b\u255f \u2588\u2584     ~\u2566%\u2592\u25654^
    
                                    \u258c\u258c  "M\u2588 `\u2580\u2555 X\u2555"\u2557\u2584\u2580^
    
                                    \u2588\u258c   \u2553M   \u2559\u2580e\u2580\u2580^
    
                                    \u2559\u2588\u2588\u2584\u2584\u2580
    
                                      ^^
    
    
    
    Remove xonsh/lexer_table.py
    
    Remove xonsh/parser_table.py
    
    Building lexer and parser tables.
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-z0uet8y1/xonsh/setup.py", line 95, in <module>
    
        main()
    
      File "/tmp/pip-build-z0uet8y1/xonsh/setup.py", line 35, in main
    
        with open('readme.rst', 'r') as f:
    
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z0uet8y1/xonsh

```

**Comment by paradoxxxzero** [comment]
The readme.rst is not packaged.

![screenshot from 2015-03-09 10 45 26](https://cloud.githubusercontent.com/assets/271144/6552758/ce7d9424-c649-11e4-9feb-a7d062052924.png)

**Comment by andybak** [comment]
I'm getting a different error on Mac using Python 2.7:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)

Shall I open a separate ticket?

**Comment by paradoxxxzero** [comment]
I think this is python 3.4 only

**Comment by aufrank** [comment]
I get the error on Mac using Python 3.4
```
$ pip3 --version
pip 6.0.8 from /usr/local/lib/python3.4/site-packages/pip-6.0.8-py3.4.egg (python 3.4)
```

```
$ python3 --version
Python 3.4.3
```

```
$ pip3 install xonsh
...
...
    Remove xonsh/lexer_table.py

    Remove xonsh/parser_table.py

    Building lexer and parser tables.

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/s5/26t2nwqj04938dgj3fv9yc0x4m8v8_/T/pip-build-_c7rhhvl/xonsh/setup.py", line 95, in <module>

        main()

      File "/private/var/folders/s5/26t2nwqj04938dgj3fv9yc0x4m8v8_/T/pip-build-_c7rhhvl/xonsh/setup.py", line 35, in main

        with open('readme.rst', 'r') as f:

    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'
```

**Comment by scopatz** [comment]
Thanks for solving this.  Let me know if I need to push a new pip package.

**Comment by paradoxxxzero** [comment]
Yeah I think a 0.1.1 wouldn't hurt

**Comment by scopatz** [comment]
@paradoxxxzero v0.1.1 is out!

**Comment by paradoxxxzero** [comment]
And now it works :+1:

**Comment by scopatz** [comment]
Awesome!
