### ISSUE TITLE
Install Requires ply and readline?

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#1018]
I have created a new Python3.5 venv and installed ```xonsh```.

```shell
running install
    Traceback (most recent call last):
      File "/tmp/pip-build-it6z1fsu/xonsh/xonsh/parsers/base.py", line 6, in <module>
        from ply import yacc
    ImportError: No module named 'ply'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-it6z1fsu/xonsh/setup.py", line 182, in <module>
        main()
      File "/tmp/pip-build-it6z1fsu/xonsh/setup.py", line 178, in main
        setup(**skw)
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-it6z1fsu/xonsh/setup.py", line 92, in run
        build_tables()
      File "/tmp/pip-build-it6z1fsu/xonsh/setup.py", line 53, in build_tables
        from xonsh.parser import Parser
      File "/tmp/pip-build-it6z1fsu/xonsh/xonsh/parser.py", line 8, in <module>
        from xonsh.parsers.v35 import Parser
      File "/tmp/pip-build-it6z1fsu/xonsh/xonsh/parsers/v35.py", line 4, in <module>
        from xonsh.parsers.base import BaseParser
      File "/tmp/pip-build-it6z1fsu/xonsh/xonsh/parsers/base.py", line 8, in <module>
        from xonsh.ply import yacc
    ImportError: No module named 'xonsh.ply'
    Remove xonsh/parser_table.py
    Building lexer and parser tables.
    
    ----------------------------------------
Command "/home/cody/Desktop/xonsh/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-it6z1fsu/xonsh/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ixx1cdg2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/cody/Desktop/xonsh/include/site/python3.5/xonsh" failed with error code 1 in /tmp/pip-build-it6z1fsu/xonsh
```

If I do ```pip install ply``` and then ```pip install xonsh``` I get an error about ```readline```.
```
(xonsh) ~/Desktop $ xonsh
Could not find xonsh configuration or run control files.
UnboundLocalError: local variable 'readline' referenced before assignment
(xonsh) cody@cody ~/Desktop $ 
```

If I install readline there is no error and the prompt is normal.

```shell
(xonsh) ~/Desktop $ pip install readline
Collecting readline
  Downloading readline-6.2.4.1.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 432kB/s 
Installing collected packages: readline
  Running setup.py install for readline ... done
Successfully installed readline-6.2.4.1
(xonsh) ~/Desktop $ xonsh
Could not find xonsh configuration or run control files.
Would you like to run the xonsh configuration wizard now?

1. Yes
2. No, but ask me later.
3. No, and don't ask me again.

1, 2, or 3 [default: 2]? 3
(xonsh) cody@cody ~/Desktop $ 
```

**Comment by scopatz** [comment]
Hi @Siecje - Sorry about this.  I believe that #1002 addresses the PLY install issue. Sorry about that!

The readline one is new to me though.  Do you have a full traceback so that we can try to debug it? Thanks!

**Comment by Siecje** [comment]
I don't it just makes the prompt those weird characters.

**Comment by scopatz** [comment]
Hi @Siecje - I meant this:

```console
(xonsh) ~/Desktop $ xonsh
Could not find xonsh configuration or run control files.
UnboundLocalError: local variable 'readline' referenced before assignment
```

Also, what is the value of `$XONSH_STORE_STDOUT`?

**Comment by Siecje** [comment]
That message isn't appearing anymore.

```$XONSH_STORE_STDOUT``` is ```False```.

I think this issue should be closed.
