### ISSUE TITLE
Not a directory '/usr/local/bin/apm' on failed commands

### ISSUE THREAD

**Issue by smogg** [scopatz/xonsh#1050]
Sooo, running 
`yolo-command` 
results in
`NotADirectoryError: [Errno 20] Not a directory: '/usr/local/bin/apm'`
Installing Atom Package Manager (`apm`) fixes the error, and another appears:

`NotADirectoryError: [Errno 20] Not a directory: '/usr/local/bin/N1`

Am I missing some dependencies?

**Comment by gforsyth** [comment]
Hey @smogg -- not sure what's going on there.  What is `yolo-command`?  Neither that nor `apm` is a part of `xonsh`.  

Does the directory `/usr/local/bin/N1` actually exist?

**Comment by adqm** [comment]
Also, can you try setting `$XONSH_SHOW_TRACEBACK = True` in your `.xonshrc` file?  That should cause a more complete traceback to show up so we can see where this issue is coming from.  Can you paste that here?

**Comment by smogg** [comment]
oh, sorry - I should have been more clear about that. The `yolo` part is basically something that should produce an error (this command does not exist, I get the `NotADirectoryError` in place of any other error I should get).
The directory does not exist, I don't know what package `N1` is (I just assumed it's some dependency I'm missing?).

**Comment by smogg** [comment]
Here's full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 536, in run_subproc
    **subproc_kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'real-command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/base_shell.py", line 154, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/local/lib/python3.5/site-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "/usr/local/lib/python3.5/site-packages/xontrib/prompt_ret_code.xsh", line 1, in <module>
    from xonsh.tools import ON_WINDOWS
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 671, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 543, in run_subproc
    sug = suggest_commands(cmd, ENV, builtins.aliases)
  File "/usr/local/lib/python3.5/site-packages/xonsh/tools.py", line 369, in suggest_commands
    for _file in executables_in(path):
  File "/usr/local/lib/python3.5/site-packages/xonsh/tools.py", line 330, in executables_in
    yield from (x.name for x in scandir(path)
  File "/usr/local/lib/python3.5/site-packages/xonsh/tools.py", line 331, in <genexpr>
    if x.is_file() and os.access(x.path, os.X_OK))
```

**Comment by adqm** [comment]
@smogg, you shouldn't need anything installed other than Python itself (and either readline or prompt_toolkit), so it's not coming from a missing dependency.

Thanks for reporting!  We'll try to look into this soon.

**Comment by mattbowen** [comment]
FWIW, I had the same error on OS X 10.11.5 running xonsh via conda ('xonsh/0.3.2',) on python 3.5.1. For me `/usr/local/bin/apm` is 

`lrwxr-xr-x    1 mrbowen  admin        80 Dec 29 05:49 apm -> /Applications/Nylas N1.app/Contents/Resources/app.asar/apm/node_modules/.bin/apm`

I stopped using Nylas N1 a little bit ago (was just playing with it anyway), so I just deleted it and unlinked that file, which "fixed" the problem.

**Comment by smogg** [comment]
@mattbowen yup, that was Nylas app causing the issue - thank you.
That is clearly not a xonsh issue so I'm closing this issue
