### ISSUE TITLE
xonsh won't start: KeyError with CANON_SHELL_NAMES[shell]

### ISSUE THREAD

**Issue by sboisen** [scopatz/xonsh#1055]
Background:

- I'm on OS X
- I installed xonsh like so (I use Python 2, but found this suggestion for installing in virtualenv at https://news.ycombinator.com/item?id=9207738)
```
brew install python3                                        # install python3 but don't make it default
cd local && mkdir xonsh && cd xonsh
virtualenv -p /usr/local/bin/python3 venv
source venv/bin/activate
pip install xonsh
xonsh
```
- That all went fine, and I went through the lengthy configuration dialog. I mostly just accepted the defaults as i recall, but i didn't track all the details. I saved the configuration. 
- I closed that shell and restarted: now i get the error below. 

I dug into the code a bit interactively, and sure enough, `shell` has the empty string and it's not in CANON_SHELL_NAMES. But I don't see where things are going wrong, or how to restore sanity. I deleted the virtualenv and created a new one, again doing pip install xonsh, thinking that might reset the state. But i still get the same error. 

Any suggestions for how to resolve or diagnose this problem? 

----
```
(venv) ws2107:xonsh sboisen$ xonsh
Traceback (most recent call last):
  File "/Users/sboisen/local/xonsh/venv/bin/xonsh", line 11, in <module>
    sys.exit(main())
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/main.py", line 228, in main
    args = premain(argv)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/main.py", line 215, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/shell.py", line 44, in __init__
    kwargs.get('cacheall', False))
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/shell.py", line 83, in _init_environ
    self.execer = Execer(config=config, login=self.login, xonsh_ctx=self.ctx)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/execer.py", line 42, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/environ.py", line 1376, in default_env
    issue_warning=False)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 506, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/Users/sboisen/local/xonsh/venv/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 217, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
KeyError: ''
(venv) ws2107:xonsh sboisen$
```

**Comment by gforsyth** [comment]
Hey @sboisen -- we use `XDG_CONFIG_HOME` to store configuration data and that would persist even if you deleted your virtualenv and recreated it.  The internet says that on OSX, `XDG_CONFIG_HOME` lives in `~/Library/Preferences` -- there should be a `xonsh` folder in there that will have a `config.json` file that may hold the answers to your empty `shell` problem.  
Or alternatively, just nuke that file and start `xonsh` and skip the wizard and see if it loads without issue.

**Comment by sboisen** [comment]
Thanks @gforsyth: those details didn't quite line up (i don't have that envar, and there's no `xonsh` folder in `~/Library/Preferences`), but eventually i did find `~/.config/xonsh/config.json`, with an empty value for `shell`. Nuking that file solved the problem.
