### ISSUE TITLE
less isn't compatible with xonsh

### ISSUE THREAD

**Issue by GMLudo** [scopatz/xonsh#106]
Hi,

I can't use `less` command in xonsh.
When I launch, the console is frozen.
After a CTRL+C, I see less, but it's incontrolable.
After another CTRL+C, I've this stacktrace + the output of the console is completely broken.
As workaround, I use `most`, I works as a charm, and it's better than `less`.

    Traceback (most recent call last):
    File "/usr/local/bin/xonsh", line 3, in <module>
    Traceback (most recent call last):
        main()
    File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 27, in main
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 109, in default
        self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
        return exec(code, glbs, locs)
        shell.default(args.command)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 105, in default
    File "<xonsh-code>", line 1, in <module>
        code = self.push(line)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 126, in push
        locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
        tree = self.parse(input, ctx, mode=mode)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 383, in subproc_uncaptured
        return run_subproc(cmds, captured=False)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 366, in run_subproc
        prev_proc.communicate()[0]
        tree = self._parse_ctx_free(input, mode=mode)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
        mode=mode, debug_level=self.debug_level)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
        debug=debug_level)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 265, in parse
    File "/usr/lib/python3.4/subprocess.py", line 941, in communicate
        self.wait()
    File "/usr/lib/python3.4/subprocess.py", line 1536, in wait
        (pid, sts) = self._try_wait(0)
    File "/usr/lib/python3.4/subprocess.py", line 1493, in _try_wait
        (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
    File "/usr/lib/python3.4/subprocess.py", line 487, in _eintr_retry_call
        return func(*args)
        return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 921, in parseopt_notrack
    KeyboardInterrupt
        lookahead = get_token()     # Get the next token
    File "/usr/local/lib/python3.4/dist-packages/xonsh/lexer.py", line 66, in token
        self.last = self.lexer.token()
    KeyboardInterrupt

**Comment by scopatz** [comment]
Hi @GMLudo - Thanks for reporting. I use less all the time, so I am not sure what is going on here. What is weirder is that the other pagers work.  Can you tell us a little about your system? OS, how you got python? etc.

**Comment by GMLudo** [comment]
I use a Kubuntu 14.04 with xonsh installed system-wide with `sudo pip3 install xonsh`.
I use xonsh in yakuake.
I've the same behaviour in konsole.
To test xonsh as a replacement of bash, I've changed my default shell in `/etc/passwd`:

    lg:x:1000:1000:Ludovic Gasc,,,:/home/lg:/usr/local/bin/xonsh

Do you need more information ?

**Comment by scopatz** [comment]
That should be enough to get started, thanks!

**Comment by scopatz** [comment]
Hmm I just tried this with yakuake, with xonsh as my default shell and with bash as my default shell and then starting xonsh.  less worked just fine for me.

**Comment by GMLudo** [comment]
ok :-(
It's very strange, I'll try on another computers to see if I find something.
In fact, it isn't really a problem, I use most that is really better compare to less.
Thanks for your test.

**Comment by GMLudo** [comment]
I've another strange behaviour with `rst2html.py` from docutils, with similar sympthoms.
I've an issue with my computer, or it's another bug ?

    lg@steroids ~/Documents/IDEA/c2c-ws $ rst2html.py 




    ^CTraceback (most recent call last):
    File "/home/lg/Documents/IDEA/c2c-ws/pyvenv/bin/rst2html.py", line 23, in <module>
    Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
        mode=mode, debug_level=self.debug_level)
        publish_cmdline(writer_name='html', description=description)
    File "/home/lg/Documents/IDEA/c2c-ws/pyvenv/lib/python3.4/site-packages/docutils/core.py", line 352, in publish_cmdline
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
        debug=debug_level)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 265, in parse
        return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 1047, in parseopt_notrack
        tok = self.errorfunc(errtoken)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
        column=self.lexer.token_col(p)))
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
        raise err
    File "<string>", line None
    SyntaxError: <xonsh-code>:1:2259: ('code: ,',)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
        config_section=config_section, enable_exit_status=enable_exit_status)
    File "/home/lg/Documents/IDEA/c2c-ws/pyvenv/lib/python3.4/site-packages/docutils/core.py", line 217, in publish
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 152, in cmdloop
        super(Shell, self).cmdloop(intro=intro)
    File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
        stop = self.onecmd(line)
    File "/usr/lib/python3.4/cmd.py", line 211, in onecmd
        return self.default(line)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 105, in default
        code = self.push(line)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 126, in push
        locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
        tree = self.parse(input, ctx, mode=mode)
        self.settings)
    File "/home/lg/Documents/IDEA/c2c-ws/pyvenv/lib/python3.4/site-packages/docutils/readers/__init__.py", line 71, in read
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
        tree = self._parse_ctx_free(input, mode=mode)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 142, in _parse_ctx_free
        returnline=True, lexer=self.parser.lexer)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/tools.py", line 55, in subproc_toks
        pos = tok.lexpos
    KeyboardInterrupt
        self.input = self.source.read()

    During handling of the above exception, another exception occurred:

    File "/home/lg/Documents/IDEA/c2c-ws/pyvenv/lib/python3.4/site-packages/docutils/io.py", line 261, in read
    Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
        mode=mode, debug_level=self.debug_level)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
        debug=debug_level)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 265, in parse
        return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
    File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 1047, in parseopt_notrack
        tok = self.errorfunc(errtoken)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
        column=self.lexer.token_col(p)))
        data = self.source.buffer.read()
    File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
        raise err
    File "<string>", line None
    KeyboardInterrupt
    SyntaxError: <xonsh-code>:1:4506: ('code: ,',)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 152, in cmdloop
        super(Shell, self).cmdloop(intro=intro)
    File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
        stop = self.onecmd(line)
    File "/usr/lib/python3.4/cmd.py", line 211, in onecmd
        return self.default(line)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 105, in default
        code = self.push(line)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 126, in push
        locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
        tree = self.parse(input, ctx, mode=mode)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
        tree = self._parse_ctx_free(input, mode=mode)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 142, in _parse_ctx_free
        returnline=True, lexer=self.parser.lexer)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/tools.py", line 54, in subproc_toks
        for tok in lexer:
    File "/usr/local/lib/python3.4/dist-packages/xonsh/lexer.py", line 86, in __iter__
        t = self.token()
    File "/usr/local/lib/python3.4/dist-packages/xonsh/lexer.py", line 66, in token
        self.last = self.lexer.token()
    File "/usr/local/lib/python3.4/dist-packages/ply/lex.py", line 319, in token
        m = lexre.match(lexdata,lexpos)
    KeyboardInterrupt

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 109, in default
        self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
        return exec(code, glbs, locs)
    File "<xonsh-code>", line 1, in <module>
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 383, in subproc_uncaptured
        return run_subproc(cmds, captured=False)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 366, in run_subproc
        prev_proc.communicate()[0]
    File "/usr/lib/python3.4/subprocess.py", line 941, in communicate
        self.wait()
    File "/usr/lib/python3.4/subprocess.py", line 1536, in wait
        (pid, sts) = self._try_wait(0)
    File "/usr/lib/python3.4/subprocess.py", line 1493, in _try_wait
        (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
    File "/usr/lib/python3.4/subprocess.py", line 487, in _eintr_retry_call
        return func(*args)
    KeyboardInterrupt
    lg@steroids ~/Documents/IDEA/c2c-ws $

**Comment by wrywerytwreywery** [comment]
Hi @GMLudo,  I believe this issue has been resolved on the current master (1ff8b24cdf070125a36818ada55b052ac244ec59).  Can you please try and confirm?

**Comment by GMLudo** [comment]
Hi @wrywerytwreywery, I've just tested 0.1.4 release, it runs like a charm, thank you a lot for your follow-up.
