### ISSUE TITLE
Parse error for `cd -`, `cd ..`, `ls ..` when inside functions

### ISSUE THREAD

**Issue by SmartViking** [scopatz/xonsh#111]
```
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   cd
............................................. 
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   cd
.............................................   return
............................................. 
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   cd --help
............................................. 
uglemat@uglemat ~/Public/xonsh/xonsh master $ f()
cd: no such file or directory: --help
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   cd -
............................................. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 137, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
    column=self.lexer.token_col(p)))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:10: ('code: (',)
uglemat@uglemat ~/Public/xonsh/xonsh master $ $[cd -]
uglemat@uglemat ~ $ cd -
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   cd ..
............................................. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 137, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
    column=self.lexer.token_col(p)))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:10: ('code: (',)
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f():
.............................................   ls ..
............................................. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 137, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
    column=self.lexer.token_col(p)))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:10: ('code: (',)
uglemat@uglemat ~/Public/xonsh/xonsh master $ def f(): ls ..
............................................. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 137, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2119, in p_error
    column=self.lexer.token_col(p)))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 341, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:10: ('code: (',)
uglemat@uglemat ~/Public/xonsh/xonsh master $ 
```

As you can see the problems begin when `cd/ls` is followed by symbol-stuff like `..`.

**Comment by wrywerytwreywery** [comment]
This is not a fix, but in the short term, you can use the `$[...]` syntax to force subprocess mode inside of functions and scripts, e.g.:

```
xonsh ~/xonsh $ def f():
...............     $[cd ..]
............... 
xonsh ~/xonsh $ f()
xonsh ~ $ def f():
.........     $[cd -]
......... 
xonsh ~ $ f()
xonsh ~/xonsh $ f()
xonsh ~ $ 
```

**Comment by scopatz** [comment]
I can reproduce this behavior, @SmartViking.

**Comment by scopatz** [comment]
Thanks for reporting.

**Comment by scopatz** [comment]
I believe that this is fixed by #167

**Comment by SmartViking** [comment]
Unfortunately it seems to halt:

    uglemat@uglemat ~ $ def f():
    ...................   cd -
    ................... 
    
    
    
    ^C 
    uglemat@uglemat ~ $ def f():
    ...................   $[cd -]
    ................... 
    uglemat@uglemat ~ $

**Comment by scopatz** [comment]
What if you do:

```python
def f():
    ls ..
```

**Comment by SmartViking** [comment]
The problem seems to be fixed on current master.
