### ISSUE TITLE
In .xonshrc, import does not create a global name

### ISSUE THREAD

**Issue by abadger** [scopatz/xonsh#131]
xonsh: git checkout f44013b31756ba5491f2a7e1dffb7ad64513b28e
python: 3.4.1
OS: Fedora 21

With this as your .xonshrc:

``` python
import subprocess

def get_tty():
    tty = subprocess.check_output('tty').decode().strip()
    segments = tty.split('/')
    return '/'.join(segments[-2:])

$PROMPT='{tty}@{{hostname}}$ '.format(tty=get_tty())
```

Trying to start .xonshrc yields a traceback:

```
Traceback (most recent call last):
  File "scripts/xonsh", line 3, in <module>
    main()
  File "/srv/git/wishlist/xonsh/xonsh/main.py", line 36, in main
    shell = Shell()
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 94, in __init__
    execer=self.execer)
  File "/srv/git/wishlist/xonsh/xonsh/environ.py", line 168, in xonshrc_context
    execer.exec(rc, glbs={}, locs=env)
  File "/srv/git/wishlist/xonsh/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "/home/badger/.xonshrc", line 7, in <module>
    
  File "/home/badger/.xonshrc", line 259, in get_tty
NameError: name 'subprocess' is not defined
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0x7f383127e4e0>>
Traceback (most recent call last):
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 102, in __del__
    teardown_readline()
  File "/srv/git/wishlist/xonsh/xonsh/shell.py", line 65, in teardown_readline
    import readline
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1908, in _get_spec
TypeError: 'NoneType' object is not iterable
```

If I change .xonshrc to have the subprocess import inside of the function then it starts up fine.  So it seems like importing does not create a globally available name.  The other things I tried such as:

``` python
import subprocess as subprocess
subprocess = __import__('subprocess')
```

also lead to the same traceback.

**Comment by scopatz** [comment]
@abadger - let us know if this fixes the problem.  Please re-open if it doesn't

**Comment by abadger** [comment]
Yep, fixed!  Thanks.
