### ISSUE TITLE
Lexer freeze

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#134]
I have this little beauty in my .xonshrc

```python
def foo():
    ascii_art = [
        "(╯°□°）╯︵ ┻━┻",
        "¯\_(ツ)_/¯",
        "┻━┻︵ \(°□°)/ ︵ ┻━┻",
    ]

    import random
    i = random.randint(0,len(ascii_art)) - 1
    print("    Get to work!")
    print(ascii_art[i])

foo()
```

When I run my terminal, it hangs forever. The prompt is never shown. When I interrupt with ctrl+c, I get the following stack trace

```
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 123, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
    main()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 36, in main
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 476, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 456, in run_subproc
    prev_proc.communicate()[0]
    shell = Shell()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 94, in __init__
  File "/usr/lib/python3.4/subprocess.py", line 941, in communicate
    self.wait()
  File "/usr/lib/python3.4/subprocess.py", line 1536, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.4/subprocess.py", line 1493, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib/python3.4/subprocess.py", line 487, in _eintr_retry_call
    return func(*args)
    execer=self.execer)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/environ.py", line 168, in xonshrc_context
KeyboardInterrupt
    execer.exec(rc, glbs={}, locs=env)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 107, in exec
    stacklevel=stacklevel)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 286, in parse
    debug=debug_level)
  File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python3.4/dist-packages/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 2040, in p_subproc_atoms
    if len(p) < 4:
KeyboardInterrupt
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0x7f81c4718518>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 102, in __del__
    teardown_readline()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 65, in teardown_readline
    import readline
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2199, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2141, in _find_spec
  File "<frozen importlib._bootstrap>", line 1917, in find_spec
  File "<frozen importlib._bootstrap>", line 1885, in _get_spec
TypeError: 'NoneType' object is not iterable
```

By coincidence I managed to solve the issue by removing the blank line in the function definintion, like so

```python
def foo():
    ascii_art = [
        "(╯°□°）╯︵ ┻━┻",
        "¯\_(ツ)_/¯",
        "┻━┻︵ \(°□°)/ ︵ ┻━┻",
    ]
    import random
    i = random.randint(0,len(ascii_art)) - 1
    print("    Get to work!")
    print(ascii_art[i])

foo()
```

with this change, it works, no problem. I tried the blank line with four space indent to match the functions indentation and with a completely blank line. Both hang.

**Comment by scopatz** [comment]
I can confirmed this behaviour.  Thanks for the report!

**Comment by wrywerytwreywery** [comment]
Hi @eldamir,  I think this should be resolved now on the current master (588fa2b377ff91af44dd11c10749697797d223ab).  Can you please verify?

**Comment by eldamir** [comment]
Sry for the late reply. Yes, it does work for me.

**Comment by scopatz** [comment]
Thanks for confirming @eldamir
