### ISSUE TITLE
Commands that start with '/' or './' result in exception

### ISSUE THREAD

**Issue by pdavydov108** [scopatz/xonsh#135]
Hello, I updated xonsh to a new verson today (via `pip`), I think it's 0.1.3 now. If I type `ls` it works just fine, but `/bin/ls` returns an exception:
````
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 123, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 476, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 412, in run_subproc
    aliased_cmd = get_script_subproc_command(cmd[0], cmd[1:])
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 359, in get_script_subproc_command
    first_line = f.readline().strip()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 24: invalid continuation byte
````
Same error occurs if I execute `./a.out`, but with different message:
````
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 24: invalid start byte
````
It worked fine in previous version.

Update: it looks like it only happens for compiled executables. Python scripts work normally for example.

**Comment by scopatz** [comment]
Thanks for reporting @pdavydov108

**Comment by scopatz** [comment]
Hi @pdavydov108 - I believe that the current master (bac6bfb) should fix this issue.

**Comment by scopatz** [comment]
Would you please verify and let us know! Thanks.

**Comment by pdavydov108** [comment]
Hi @scopatz ! I've installed the current master (1e76fd076575c3c3d9706e337ef9aa6d41fabe3a) and it works just fine, thanks.
