### ISSUE TITLE
Weird behavior after ctrl-c in gdb or pdb

### ISSUE THREAD

**Issue by pdavydov108** [scopatz/xonsh#139]
If I start `gdb` or `pdb` from xonsh and hit `ctrl-c`, I first get `KeyboardInterrupt` message, and then normal xonsh prompt is printed, but if I press enter button, it outputs either xonsh or gdb prompt in random order. In fact, gdb never exits on ctrl-c, in bash it just prints `Quit` in it's shell.
````
(gdb) Quit
(gdb) Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 123, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 476, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 456, in run_subproc
    prev_proc.communicate()[0]
  File "/usr/lib/python3.4/subprocess.py", line 952, in communicate
    self.wait()
  File "/usr/lib/python3.4/subprocess.py", line 1566, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.4/subprocess.py", line 1514, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
pablo@alien ~ $ pablo@alien ~ $ 
(gdb) pablo@alien ~ $ pablo@alien ~ $ 
(gdb) 
(gdb) pablo@alien ~ $ 
(gdb) Quit
(gdb) Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 123, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 476, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 456, in run_subproc
    prev_proc.communicate()[0]
  File "/usr/lib/python3.4/subprocess.py", line 952, in communicate
    self.wait()
  File "/usr/lib/python3.4/subprocess.py", line 1566, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.4/subprocess.py", line 1514, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
pablo@alien ~ $ pablo@alien ~ $ 
(gdb) pablo@alien ~ $ pablo@alien ~ $ 
(gdb) 
(gdb) pablo@alien ~ $ 
````
If I then press ctrl-d (to exit gdb) and `reset` xonsh returns to normal behavior.

**Comment by scopatz** [comment]
Hi yes, this is a weird issue where Crtl-C isn't getting captured at the right place in a subprocess.

**Comment by wrywerytwreywery** [comment]
I have noticed this same behavior as well with certain programs (mutt and less for me).  It seems like the shell is receiving that signal and acting on it, even when the program in between the user and the shell is ignoring it.

**Comment by scopatz** [comment]
I think I might know a fix.  I'll give it a try.

**Comment by scopatz** [comment]
Also, you are right @wrywerytwreywery - this is very much not specific to gdb

**Comment by scopatz** [comment]
Ok @pdavydov108 and @wrywerytwreywery - I believe that the current master (1e76fd0) fixes this.  Could you confirm, please?

**Comment by wrywerytwreywery** [comment]
Seems to work for me!

**Comment by pdavydov108** [comment]
Works for me too! Thanks for quick fix @scopatz .
