### ISSUE TITLE
Parser error on import *

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#154]
Well, that is one way to prevent bad behaviour :)

```console
scopatz@athenaie ~ $ from sys import *
Traceback (most recent call last):
  File "/home/scopatz/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/main.py", line 69, in main
    shell.cmdloop()
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/shell.py", line 167, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/home/scopatz/miniconda3/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/scopatz/miniconda3/lib/python3.4/cmd.py", line 211, in onecmd
    return self.default(line)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/shell.py", line 119, in default
    code = self.push(line)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/shell.py", line 140, in push
    locs=self.ctx)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 85, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 73, in parse
    tree = self.ctxtransformer.ctxvisit(tree, input, ctx, mode=mode)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/ast.py", line 80, in ctxvisit
    node = self.visit(node)
  File "/home/scopatz/miniconda3/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/scopatz/miniconda3/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/scopatz/miniconda3/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/ast.py", line 169, in visit_ImportFrom
    if name.asname is None:
AttributeError: 'str' object has no attribute 'asname'
```

**Comment by scopatz** [comment]
closed by #156
