### ISSUE TITLE
xonsh equivalent of "source"?

### ISSUE THREAD

**Issue by shoyer** [scopatz/xonsh#16]
I'd like to use conda environments with xonsh. These are usually invoked with `source activate my-environment`, but that doesn't work with xonsh:

```
shoyer@tcc-shoyer.local ~ $ source activate my-env
Traceback (most recent call last):
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/xonsh/shell.py", line 142, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/xonsh/shell.py", line 92, in default
    self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/xonsh/execer.py", line 108, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 0, in <module>
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/xonsh/built_ins.py", line 343, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/xonsh/built_ins.py", line 313, in run_subproc
    stdin=stdin, stdout=stdout)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'source'
```

**Comment by scopatz** [comment]
Hmm ``source`` is a bash built-in command.  What does activate do exactly?  Inside of the activate source code it says `"Only bash and zsh are supported"`.  It is worth figuring out.  It seems like we should be able to write an activate alias for you.

**Comment by scopatz** [comment]
And I'll also try to think of a meaningful way to source bash scripts.  I think I know a way... But 2 am is not the time to test it :)

**Comment by shoyer** [comment]
Note that `venv`/`virtualenv` uses `source` in a similar way to switch between environments.

**Comment by scopatz** [comment]
Thanks @shoyer - good to know. I don't use this aspect of those tools, but I agree that it is important to support.  Would you be opposed to writing `bash-source activate myenv`?

**Comment by shoyer** [comment]
Sure, that seems reasonable to me.

**Comment by scopatz** [comment]
I might go with `source-bash`, actually, so people who search for this or start tab-completing will get the right thing.

**Comment by scopatz** [comment]
Ok! In 71e95fa I added an experimental `source-bash` functionality.  I have tested it with some local shell files but not with conda.  Can you try running:

```console
$ source-bash activate myenv
```

**Comment by shoyer** [comment]
I'll need to add some tweak so that the command prompt changes as it does in bash/zsh... but it works! Thanks!

**Comment by scopatz** [comment]
Oh right!  Because this changes your $PS1, and xonsh uses the $PROMPT variable.  Let me know if you run into problems, but I am glad that it *mostly* works.

**Comment by scopatz** [comment]
The following would probably work, if you stuck this in the ~/.xonshrc

```python
import builtins

$PROMPT = lambda: builtins.__xonsh_env__.get('PS1', '>>> ')
```

You could make this fancier, obviously.
