### ISSUE TITLE
Parser error for  "ls file; ls file"

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#167]
So `ls file; ls file` will now enter multiline mode, and then fail.  Defining a function will similarly fail:

```console
scopatz@athenaie ~ $ def f():
`·.,¸,.·*¯`·.,¸,.·*¯     ls file
`·.,¸,.·*¯`·.,¸,.·*¯     ls file
`·.,¸,.·*¯`·.,¸,.·*¯ 
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 125, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 282, in parse
    debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 2154, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 351, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:2:0: ('code: $[',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/shell.py", line 141, in push
    locs=self.ctx)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 89, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 67, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 156, in _parse_ctx_free
    raise original_error
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/execer.py", line 125, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 282, in parse
    debug=debug_level)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 2154, in p_error
    column=p.lexpos))
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/parser.py", line 351, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:2:7: ('code: file',)
```

Looks like the execer still needs some work :)

**Comment by wrywerytwreywery** [comment]
I won't have time to look at this for a while, but printing the values fed to `Lexer.input` gives some clue:
```
>>> echo "hey"
input 'echo "hey"\n'
input 'echo "hey"'
input '$[echo "hey"]\n'
hey
>>> echo "hey" ;
input 'echo "hey" ;\n'
input 'echo "hey" ;'
input '$[echo "hey"] ;\n'
hey
>>> echo "hey" ; echo "Hey"
input 'echo "hey" ; echo "Hey"\n'
input 'echo "hey" ; echo "Hey"'
input '$[echo "hey" ]; echo "Hey"\n'
```

I do remember messing around with the treatment of semicolons in `subproc_toks`.  Hopefully not, but I may have broken something there.

**Comment by scopatz** [comment]
I'll take a look later tonight.

**Comment by scopatz** [comment]
I just didn't want to forget.

**Comment by scopatz** [comment]
@wrywerytwreywery I think that the `subproc_toks()` function is OK since there are test cases that cover this and pass.
