### ISSUE TITLE
Stdin option not working 

### ISSUE THREAD

**Issue by blink1073** [scopatz/xonsh#172]
I am attempting to make a simple `Xonsh` Jupyter Kernel using [Metakernel](https://pypi.python.org/pypi/metakernel) (which provides a standard set of magics).  I have a rough implementation [here](https://gist.github.com/blink1073/4289a9393880b5d3e74b).  I tried to follow along with the `stdin` option in `main.py`, but ran into an issue [here](https://gist.github.com/blink1073/4289a9393880b5d3e74b#file-gistfile1-txt-L57), which can be readily seen:

```bash
$ echo "ls" | xonsh
Traceback (most recent call last):
  File "/Users/stevensilvester/anaconda/bin/xonsh", line 3, in <module>
    main()
  File "/Users/stevensilvester/anaconda/lib/python3.4/site-packages/xonsh/main.py", line 61, in main
    code = shell.execer.compile(code, mode='exec', glbs=shell.ctx)
  File "/Users/stevensilvester/anaconda/lib/python3.4/site-packages/xonsh/execer.py", line 92, in compile
    code = compile(tree, self.filename, mode)
TypeError: expected some sort of stmt, but got <_ast.Call object at 0x103097080
```

I am using Python 3.4 on OSX.

**Comment by blink1073** [comment]
It *almost* works if I detect the `TypeError`, and add `$()` around it.  However, is there a way to capture the stdout and stderr?  Right now I get `None` back from `compile` when I add the `$()` and the stderr is piped to the console where kernel was started.

**Comment by blink1073** [comment]
Stdout is now working if I use `eval` instead of `exec`, but it is still going to the kernel instead of the frontend.

**Comment by blink1073** [comment]
My brain is about to explode, that's enough for tonight :smile:

**Comment by scopatz** [comment]
Hi @blink1073, first off this would be amazing!  

Secondly, I think that you probably should use exec mode.  The fix for forcing exec mode instead of eval is to ensure that the input ends in a newline.  For example, you can just do something like:

```python
src = src if src.endswith('\n') else src + '\n' 
```

and then xonsh should work fine.

**Comment by wrywerytwreywery** [comment]
Hi @blink1073, also it might be worth noting that the original error you posted seems to be caused by the issue we are working on in #168.  So I don't think there's necessarily an issue with the way you're handling `stdin`; what you're seeing could be caused by that bug.  A test would be to send in `ls .` instead of `ls` and see whether that works.

**Comment by blink1073** [comment]
@wrywerytwreywery, `ls .` works as expected.  I think `xonsh` may need to be run as a subprocess (using the [process metakernel](https://github.com/blink1073/metakernel/blob/master/metakernel/process_metakernel.py#L14])), which will give us finer grain control over stdout/stderr, and avoid `exec` interfering with IPython itself, as evidenced when I `exec` `1 + 1`:

```python
In [1]: 1 + 1
Traceback (most recent call last):
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 168, in run_cell
    self.handle_input_request(msg_id, timeout=0.05)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 373, in handle_input_request
    req = self.client.stdin_channel.get_msg(timeout=timeout)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/kernel/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afrl/anaconda/envs/test/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 371, in start
    self.shell.mainloop()
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 407, in mainloop
    self.interact(display_banner=display_banner)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 568, in interact
    self.run_cell(source_raw)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 171, in run_cell
    self.handle_iopub(msg_id)
  File "/home/afrl/anaconda/envs/test/lib/python3.4/site-packages/IPython/terminal/console/interactiveshell.py", line 280, in handle_iopub
    self.execution_count = int(sub_msg["content"]["execution_count"])
KeyError: 'execution_count'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

make: *** [test] Error 1
```

**Comment by scopatz** [comment]
Any updates here @blink1073?

**Comment by scopatz** [comment]
Just wanna make sure that you aren't stuck because of something in xonsh :)

**Comment by blink1073** [comment]
I'm not stuck, just lacking cycles...
I'd still argue there is a valid bug here.  It still fails if I use `echo "$(ls)" | xonsh`.

**Comment by blink1073** [comment]
Actually, nevermind, bash is interpreting the command prior to sending it in, I'll just close this.

**Comment by blink1073** [comment]
@scopatz, she's ready!  https://github.com/Calysto/xonsh_kernel

**Comment by blink1073** [comment]
Please feel free to update the example notebook with some better content :smile:
It supports completion, help, and the standard set of magics.

**Comment by scopatz** [comment]
Cool thanks!

**Comment by scopatz** [comment]
Thanks a ton for this work @blink1073!  I've put out a call for people to test it.  Hopefully we get some feedback :)

**Comment by blink1073** [comment]
Great!  See also https://pypi.python.org/pypi/xonsh_kernel/
