### ISSUE TITLE
Exception on startup on MacOS X 10.10.2

### ISSUE THREAD

**Issue by shannonlucas** [scopatz/xonsh#18]
After installing via `pip3` on MacOS, I get an exception and stack trace whenever I try to start the shell:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/xonsh", line 3, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/main.py", line 14, in main
    shell = Shell()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/shell.py", line 76, in __init__
    setup_readline()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/shell.py", line 30, in setup_readline
    'rl_completion_suppress_append')
ValueError: dlsym(0x10069fd20, rl_completion_suppress_append): symbol not found
```

MacOS X 10.10.2
Python 3.4.3

**Comment by scopatz** [comment]
I believe that this is a duplicate of #9.  Can you confirm , @shannonlucas? Thanks

**Comment by shannonlucas** [comment]
Yes, it's a duplicate of #9.

**Comment by scopatz** [comment]
@shannonlucas 10e5147 should fix the issue, if you could confirm that'd be great!

**Comment by shannonlucas** [comment]
I pulled and installed master, but now I get a different exception:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/xonsh", line 3, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/main.py", line 14, in main
    shell = Shell()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/shell.py", line 80, in __init__
    setup_readline()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xonsh/shell.py", line 37, in setup_readline
    readline.read_history_file(hf)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by scopatz** [comment]
Ok!  Try the current master (6de56db).  This should fix it.

**Comment by shannonlucas** [comment]
That fixed it. Thanks!

**Comment by scopatz** [comment]
Great!
