### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" on first run

### ISSUE THREAD

**Issue by jalanb** [scopatz/xonsh#2]
```shell
2015-03-09 09:06:37 [alanb@moon:~/src/git/hub] [2.7.5] 50s $ 
$ git clone https://github.com/scopatz/xonsh.git
Cloning into 'xonsh'...
remote: Counting objects: 1471, done.
remote: Compressing objects: 100% (31/31), done.
Receiving objects: 100% (1471/1471), 855.02 KiB | 655.00 KiB/s, done.
remote: Total 1471 (delta 12), reused 0 (delta 0), pack-reused 1439
Resolving deltas: 100% (901/901), done.
Checking connectivity... done.

2015-03-09 09:06:44 [alanb@moon:~/src/git/hub] [2.7.5] 7s $ 
$ cd xonsh

2015-03-09 09:07:09 [alanb@moon:~/src/git/hub/xonsh] [2.7.5] master 8s 1 ± 
$ sudo python3 setup.py install

                           ╓██▄                                              
                          ╙██▀██╕                                            
                         ▐██4Φ█▀█▌                                           
                       ²██▄███▀██^██                                         
                     -███╩▀ " ╒▄█████▀█                                      
                      ║██▀▀W╤▄▀ ▐║█╘ ╝█                                      
                 ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕                            
                 "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕                           
                  ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄                          
               ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗                 
               █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █                
            ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌               
           ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫               
             ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐              
               ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌              
                ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌              
                 ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌              
                  ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M              
                  ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║               
                   ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █               
                   ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌               
                    ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █                
                     ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌                
                      ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █                 
                       ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌                 
                         ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █                  
                          `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ                  
                            ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘                   
                              █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀                     
                               █"█▌▌╟Å╓█╓█▀%`    ▄▀                          
                               ╙▌██`▒U▓U█%╗*     █                           
                                ▌╫║ ▌ÅÅ║▀╛¬`      `"█                        
                                ▌╫  ╫╟ █▄     ~╦%▒╥4^                        
                                ▌▌  "M█ `▀╕ X╕"╗▄▀^                          
                                █▌   ╓M   ╙▀e▀▀^                             
                                ╙██▄▄▀                                       
                                  ^^                                         

Remove xonsh/lexer_table.py
Remove xonsh/parser_table.py
Building lexer and parser tables.
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing top-level names to xonsh.egg-info/top_level.txt
writing dependency_links to xonsh.egg-info/dependency_links.txt
writing xonsh.egg-info/PKG-INFO
reading manifest file 'xonsh.egg-info/SOURCES.txt'
writing manifest file 'xonsh.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying xonsh/parser_table.py -> build/lib/xonsh
copying xonsh/lexer_table.py -> build/lib/xonsh
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/main.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/execer.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/parser_table.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/environ.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/lexer_table.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/ast.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/shell.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/completer.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/lexer.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/tools.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/built_ins.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/__init__.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/aliases.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/inspectors.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/parser.py -> build/bdist.linux-x86_64/egg/xonsh
copying build/lib/xonsh/openpy.py -> build/bdist.linux-x86_64/egg/xonsh
byte-compiling build/bdist.linux-x86_64/egg/xonsh/main.py to main.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/execer.py to execer.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/parser_table.py to parser_table.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/environ.py to environ.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/lexer_table.py to lexer_table.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/ast.py to ast.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/shell.py to shell.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/completer.py to completer.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/lexer.py to lexer.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/tools.py to tools.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/built_ins.py to built_ins.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/aliases.py to aliases.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/inspectors.py to inspectors.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/parser.py to parser.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/xonsh/openpy.py to openpy.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/xonsh -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/xonsh to 755
copying xonsh.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xonsh.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xonsh.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xonsh.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
xonsh.__pycache__.inspectors.cpython-34: module MAY be using inspect.getsource
xonsh.__pycache__.inspectors.cpython-34: module MAY be using inspect.getabsfile
xonsh.__pycache__.execer.cpython-34: module MAY be using inspect.stack
xonsh.__pycache__.shell.cpython-34: module references __file__
creating 'dist/xonsh-0.1-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing xonsh-0.1-py3.4.egg
removing '/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg' (and everything under it)
creating /usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg
Extracting xonsh-0.1-py3.4.egg to /usr/local/lib/python3.4/dist-packages
xonsh 0.1 is already the active version in easy-install.pth
Installing xonsh script to /usr/local/bin

Installed /usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg
Processing dependencies for xonsh==0.1
Finished processing dependencies for xonsh==0.1

2015-03-09 09:07:14 [alanb@moon:~/src/git/hub/xonsh] [2.7.5] master 5s ± 
$ xonsh
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 4, in <module>
    __import__('pkg_resources').run_script('xonsh==0.1', 'xonsh')
  File "/usr/local/lib/python3.4/dist-packages/setuptools-14.0-py3.4.egg/pkg_resources/__init__.py", line 698, in run_script
  File "/usr/local/lib/python3.4/dist-packages/setuptools-14.0-py3.4.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/EGG-INFO/scripts/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/main.py", line 14, in main
    shell = Shell()
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/shell.py", line 68, in __init__
    self.execer = Execer()
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/execer.py", line 34, in __init__
    load_builtins(execer=self)
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/built_ins.py", line 318, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env())
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/environ.py", line 121, in default_env
    ctx.update(bash_env())
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/environ.py", line 95, in bash_env
    env = dict(items)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Exception ignored in: <bound method Execer.__del__ of <xonsh.execer.Execer object at 0x7feb369314a8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/execer.py", line 37, in __del__
    unload_builtins()
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/built_ins.py", line 340, in unload_builtins
    ENV.undo_replace_env()
AttributeError: 'NoneType' object has no attribute 'undo_replace_env'
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0x7feb36878a20>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/shell.py", line 79, in __del__
    teardown_readline()
  File "/usr/local/lib/python3.4/dist-packages/xonsh-0.1-py3.4.egg/xonsh/shell.py", line 45, in teardown_readline
    import readline
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1908, in _get_spec
TypeError: 'NoneType' object is not iterable

```

**Comment by scopatz** [comment]
Hi @jalanb - what kind of system are you on? Also what does this output:

```python
$ python -c "import readline; print('yay!')"
```

**Comment by scopatz** [comment]
Ok I believe I have a fixed for this in eefe989, which is now on master. Could you try it out @jalanb and let me know if it works? Thanks!

**Comment by jalanb** [comment]
I'm on Ubuntu 12.04.5 LTS, the python I was using for that command is version 3.4.2, and am happy to say the problem is now fixed

**Comment by scopatz** [comment]
Great!
