### ISSUE TITLE
can't install xonsh on Mac OS X: UnicodeEncodeError

### ISSUE THREAD

**Issue by ischurov** [scopatz/xonsh#20]
```
[user@maccie user #2092]$ sudo pip install xonsh                                        
Downloading/unpacking xonsh
  Downloading xonsh-0.1.1.tar.gz (72kB): 72kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/xonsh/setup.py) egg_info for package xonsh
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/xonsh/setup.py", line 111, in <module>
        main()
      File "/private/tmp/pip_build_root/xonsh/setup.py", line 46, in main
        print(logo)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/xonsh/setup.py", line 111, in <module>

    main()

  File "/private/tmp/pip_build_root/xonsh/setup.py", line 46, in main

    print(logo)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)

[user@maccie user #2094]$ pip --version                                                 
pip 1.5.6 from /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)

[user@maccie user #2095]$ python --version                                              
Python 2.7.8
```

Using Mac OS X Yosemite

**Comment by ischurov** [comment]
btw,

```
[user@maccie user #2097]$ locale                                                        ~
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by scopatz** [comment]
Hi @ischurov - xonsh is currently Python 3.4+ only. I'll setup.py fail in a more meaningful way.

**Comment by scopatz** [comment]
87052bd Should cause xonsh to fail to install on Py2k.
