### ISSUE TITLE
ProcessLookupError: [Errno 3] No such process

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#201]
```pytb
$ echo $PS1
\[
\]\[\r\]\[\e[1;30;40m\]\[\e[1;37;40m\]\W\[\e[1;36;40m\]master%=\[\e[1;31;40m\]$\[\e[0m\]\[\]\[\]
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/shell.py", line 131, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/execer.py", line 124, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 551, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 520, in run_subproc
    'pgrp': os.getpgid(prev_proc.pid),
ProcessLookupError: [Errno 3] No such process
```

**Comment by wrywerytwreywery** [comment]
Thanks for reporting, @asmeurer!  I think that it is likely that this is related to the other issue you reported (#202).

I have been unable to replicate this behavior.  Is this something that always happens (regardless of what program you are trying to run), something that happens consistently when running a particular program, or something that just happens every once in a while?

Also, can you provide some information about your system?  For example, your operating system and xonsh version might be helpful, including how you installed xonsh (from pip, from current master, or from someplace else).

**Comment by asmeurer** [comment]
Mac OS X with iTerm 2 nightly. conda install -c scopatz xonsh. I haven't had time to use xonsh since this, so I can't say if it reproduces well or not.

**Comment by scopatz** [comment]
I'll try playing around with this tomorrow, on my mac.  Also, @asmeurer, what happens if you just do:

```console
$ $PS1
# or
$ print($PS1)
```

**Comment by asmeurer** [comment]
They get mixed up

```
r-packagesmaster%=$xonsh
aaronmeurer@hq-dhcp-20-62 ~/Documents/Continuum/conda-recipes/r-packages master $ $PS1
'\\[\x1b]133;D;$?\x07\x1b]1337;RemoteHost=aaronmeurer@hq-dhcp-20-62.20.10.10.in-addr.arpa\x07\x1b]1337;CurrentDir=/Users/aaronmeurer/Documents/Continuum/conda-recipes/r-packages\x07\x1b]133;A\x07\\]\\[\\r\\]\\[\\e[1;30;40m\\]\\[\\e[1;37;40m\\]\\W\\[\\e[1;36;40m\\]master%=\\[\\e[1;31;40m\\]$\\[\\e[0m\\]\\[\x1b]6;1;bg;red;brightness;255\x07\x1b]6;1;bg;blue;brightness;255\x07\x1b]6;1;bg;green;brightness;0\x07\x1b]0;\x07\\]\\[\x1b]133;B\x07\\]'
aaronmeurer@hq-dhcp-20-62 ~/Documents/Continuum/conda-recipes/r-packages master $ print($PS1)
\[
\]\[\r\]\[\e[1;30;40m\]\[\e[1;37;40m\]\W\[\e[1;36;40m\]master%=\[\e[1;31;40m\]$\[\e[0m\]\[\]\[\]
aaronmeurer@hq-dhcp-20-62 ~/Documents/Continuum/conda-recipes/r-packages master $
```

**Comment by asmeurer** [comment]
(to be clear, the final line of that is the next prompt, not part of the `print($PS1)`).
