### ISSUE TITLE
Crash after error in multi-line input

### ISSUE THREAD

**Issue by mbollmann** [scopatz/xonsh#22]
So if I'm entering something stupid, I usually get some kind of exception. For example, for a non-existant command:

```
>>> xyz
Traceback (most recent call last):
  [...]
FileNotFoundError: [Errno 2] No such file or directory: 'xyz'
>>>
```

However, the same thing in multi-line input causes xonsh to crash completely, sending me back to my default shell:

```
>>> if True:
...     xyz
...
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 15, in main
    shell.cmdloop()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 139, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.4/cmd.py", line 204, in onecmd
    return self.emptyline()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 86, in emptyline
    self.default('')
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 95, in default
    code = self.push(line)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 117, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 82, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 70, in parse
    tree = self.ctxtransformer.ctxvisit(tree, input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ast.py", line 80, in ctxvisit
    node = self.visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ast.py", line 137, in visit_Expr
    newnode = self.try_subproc_line(node)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/ast.py", line 101, in try_subproc_line
    spline = subproc_line(self.lines[node.lineno - 1])
  File "/usr/local/lib/python3.4/dist-packages/xonsh/tools.py", line 31, in subproc_line
    tok = line.split(None, 1)[0]
IndexError: list index out of range
$ 
```

Shouldn't it at least fail in a way that allows me to continue my current session?
(I was experimenting with what I can or can't do in xonsh, and having to restart it and losing any variables etc. I've set up is tiresome.)

It doesn't seem to matter what kind of error occurs within the multi-line input, and it happens both in a `if`-conditional and a `for`-loop.

**Comment by scopatz** [comment]
So this was a series of errors mostly stemming from miscalculating the current line number.  b19692d should fix it. Can you confirm @mbollmann?

**Comment by mbollmann** [comment]
Yes, seems to work now. I can also use subprocess-mode now within multi-line input, which was not previously possible. Yay!
