### ISSUE TITLE
xonsh is not robust to the presence of gnureadline

### ISSUE THREAD

**Issue by tdsmith** [scopatz/xonsh#226]
gnureadline writes a Python readline.py, which keeps xonsh from starting:

```
darkside:~ tim$ pip3 install gnureadline
Collecting gnureadline
  Using cached gnureadline-6.3.3.tar.gz
Installing collected packages: gnureadline
  Running setup.py install for gnureadline
Successfully installed gnureadline-6.3.3

darkside:~ tim$ xonsh
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/HEAD/libexec/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/Cellar/xonsh/HEAD/libexec/lib/python3.5/site-packages/xonsh/main.py", line 40, in main
    shell = Shell() if not args.norc else Shell(ctx={})
  File "/usr/local/Cellar/xonsh/HEAD/libexec/lib/python3.5/site-packages/xonsh/shell.py", line 108, in __init__
    setup_readline()
  File "/usr/local/Cellar/xonsh/HEAD/libexec/lib/python3.5/site-packages/xonsh/shell.py", line 31, in setup_readline
    RL_LIB = lib = ctypes.cdll.LoadLibrary(readline.__file__)
  File "/usr/local/Cellar/python3/3.5.0a4/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python3/3.5.0a4/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python3.5/site-packages/readline.py, 6): no suitable image found.  Did find:
	/usr/local/lib/python3.5/site-packages/readline.py: file too short
```

**Comment by scopatz** [comment]
Thanks for reporting! I think that the current windows pr has a fix for this.

**Comment by tdsmith** [comment]
Great, thanks!

**Comment by rbrewer123** [comment]
@tdsmith the windows pr is now merged and may solve this issue.

**Comment by scopatz** [comment]
If you could let us know @tdsmith, that'd be great.

**Comment by tdsmith** [comment]
Looks resolved, thanks :+1:

**Comment by scopatz** [comment]
Great!
