### ISSUE TITLE
BUG: some multi-line input crashes xonsh

### ISSUE THREAD

**Issue by shoyer** [scopatz/xonsh#26]
I just installed off of master:
```
shoyer@tcc-shoyer.local ~/dev/xonsh $ for _ in range(3):
.....................................     pass
..................................... pass
.....................................
Traceback (most recent call last):
  File "/Users/shoyer/miniconda/envs/xonsh/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/shoyer/dev/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/Users/shoyer/dev/xonsh/xonsh/main.py", line 15, in main
    shell.cmdloop()
  File "/Users/shoyer/dev/xonsh/xonsh/shell.py", line 142, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/cmd.py", line 204, in onecmd
    return self.emptyline()
  File "/Users/shoyer/dev/xonsh/xonsh/shell.py", line 86, in emptyline
    self.default('')
  File "/Users/shoyer/dev/xonsh/xonsh/shell.py", line 95, in default
    code = self.push(line)
  File "/Users/shoyer/dev/xonsh/xonsh/shell.py", line 116, in push
    locs=self.ctx)
  File "/Users/shoyer/dev/xonsh/xonsh/execer.py", line 82, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/Users/shoyer/dev/xonsh/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/Users/shoyer/dev/xonsh/xonsh/execer.py", line 116, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/Users/shoyer/dev/xonsh/xonsh/parser.py", line 268, in parse
    debug=debug_level)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/site-packages/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/Users/shoyer/dev/xonsh/xonsh/parser.py", line 394, in p_file_stmts
    p[0] = p[1] + p[2]
TypeError: can only concatenate list (not "str") to list
```

**Comment by scopatz** [comment]
I can confirm that this happens.

**Comment by scopatz** [comment]
2402b49 should fix this.  Can you confirm @shoyer? Thanks for reporting!

**Comment by shoyer** [comment]
Yes, fixed. Thanks!
