### ISSUE TITLE
windows: Xonsh only works if bash unix tools are on the path

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#281]
I am not sure if this is intentional. I tried to install xonsh on a fresh computer with windows 10.

I got an error (see below). After installing msys-git with the option that put its bash unix tools on the path the error went away. 

Will xonsh only work on windows if bash tools are avaiable?

``` 
C:\Users\Morten\Anaconda3>xonsh
Traceback (most recent call last):
  File "C:\Users\Morten\Anaconda3\Scripts\xonsh-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\main.py", line 58, in main
    shell = Shell(**shell_kwargs)
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\shell.py", line 26, in __init__
    self._init_environ(ctx)
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\shell.py", line 54, in _init_environ
    self.execer = Execer()
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\execer.py", line 41, in __init__
    load_builtins(execer=self)
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 570, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env())
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\environ.py", line 514, in default_env
    ctx.update(bash_env())
  File "C:\Users\Morten\Anaconda3\lib\site-packages\xonsh\environ.py", line 480, in bash_env
    universal_newlines=True)
  File "C:\Users\Morten\Anaconda3\lib\subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "C:\Users\Morten\Anaconda3\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Morten\Anaconda3\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by melund** [comment]
I think the problem is that the try/catch block only catches subprocess.CalledProcessError. That error is only raise if the command is available but returns a non-zero exit code. If the command is not available a FileNotFoundError is raised. I made a pull request that fix this. https://github.com/scopatz/xonsh/pull/282
