### ISSUE TITLE
Shared backreferences across regular expressions

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#308]
I don't know if this is actually a good idea or not. There may be a better way to achieve what I am after. 

Say I have a bunch of files in a directory `foo1`, `foo2`, `foo3`, ..., and I want to rename these to `bar1`, `bar2`, `bar3`, ....  This is pretty easy to represent using regular expressions, I want to replace`foo(.*)` with `bar\1`. In Xonsh, this obviously doesn't work:

```
test🐚 mv `foo(.*)` `bar\1`
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/base_shell.py", line 42, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 185, in regexpath
    return reglob(s)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 149, in reglob
    return reglob(d, parts, i=0)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/xonsh/built_ins.py", line 161, in reglob
    regex = re.compile(regex)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/re.py", line 223, in compile
    return _compile(pattern, flags)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/re.py", line 294, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/sre_compile.py", line 568, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/sre_parse.py", line 760, in parse
    p = _parse_sub(source, pattern, 0)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/sre_parse.py", line 370, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/aaronmeurer/anaconda/lib/python3.4/sre_parse.py", line 730, in _parse
    code = _escape(source, this, state)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/sre_parse.py", line 361, in _escape
    raise error("bogus escape: %s" % repr(escape))
sre_constants.error: bogus escape: '\\1'
```

It would work if the backreferences were shared between regular expression expressions. I don't know if that is easy to implement, or even a good idea, though (it would make regular expressions context sensitive, so that something like `(.)\1` would mean a different thing in isolation from after another regular expression expression with a capture). 

Or do you have other suggestions on how xonsh could make things like batch renames easier?

**Comment by adqm** [comment]
I think this is a nice idea, but I don't think it's actually too easy to implement.  It seems like what you would want, in that case, would be to expand to several different move commands (`mv foo1 bar1`, `mv foo2 bar`, etc).  I usually do something like the following:

```xsh
for i in range(5):
    mv @("foo%d" % i) @("bar%d" % i)
```

I think that should work...

Or you could use the regular expression matching:

```xsh
for i in `foo\d+`:
    mv @(i) @(i.replace('foo','bar'))
```

That said, I don't think we should abandon this, since it would be quite nice.  It will just take some thought to implement properly.

**Comment by scopatz** [comment]
The problem here, I think, is that mv only takes one DEST location. This means that if you want to move to multiple locations, you have to loop.  On the other hand, I sort of consider this a solved problem since this is what the `rename` command is for.  `rename` allows you to pass in regexes and have multiple destinations. 

Also, if you must do this in one expr, I would use the less-than-pretty list comprehension:

```python
[$[mv @(i) @(i.replace('foo', 'bar'))] for i in `foo\d+`]
```

That said, there are other instances where maybe backreferncing is a good idea. Certainly worth keeping the options open.

**Comment by asmeurer** [comment]
What is the `rename` command? I don't have that on my computer

**Comment by scopatz** [comment]
Apparently it isn't on Mac by default: http://stackoverflow.com/a/22046969/2312428

This would be a pretty easy alias to write, though. Might make a nice addition to xonsh.

**Comment by scopatz** [comment]
@asmeurer, should we close this issue in favor of a rename alias issue.?

**Comment by NorthIsUp** [comment]
ya'll need to check out zmv https://coderwall.com/p/yepegw/mass-renaming-files-with-zmv-zsh

**Comment by scopatz** [comment]
Thanks @NorthIsUp

**Comment by anki-code** [comment]
The original `` mv `foo(.*)` `bar\1` `` can't work — backtick expressions are evaluated independently, there's no way to share captures between them.

But today xonsh 0.23.0 has `` m`…` `` (match globbing) which extracts capture groups directly from the filesystem, so this becomes:

```xonsh
for s in m`./foo(.*)`:
    mv foo@(s) bar@(s)
```

`` m`./foo(.*)` `` returns `XonshList(['1', '2', '3'])` — the captured suffixes — and `@()` concatenation builds the filenames inline.

With nested groups you get both the full name and the suffix as a tuple:

```xonsh
for src, s in m`./(foo(.*))`:
    mv @(src) @(f'bar{s}')
```

`` m`./(foo(.*))`  `` → `[('foo1','1'), ('foo2','2'), ('foo3','3')]`.

Not a single-command solution, but it eliminates the manual regex boilerplate that a plain for-loop would need.
