### ISSUE TITLE
Launching release version of Xonsh crashes at `call_hg_command`

### ISSUE THREAD

**Issue by stefanv** [scopatz/xonsh#329]
```
$ xonsh
Traceback (most recent call last):
  File "/home/stefan/envs/py3/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/stefan/src/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/main.py", line 88, in main
    shell.cmdloop()
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/readline_shell.py", line 114, in cmdloop
    super().cmdloop(intro=intro)
  File "/usr/lib/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/readline_shell.py", line 127, in prompt
    return super().prompt
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/base_shell.py", line 106, in prompt
    p = format_prompt(p)
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 407, in format_prompt
    for (k, v) in fmt.items()
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 408, in <dictcomp>
    if k in included_names}
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 364, in branch_color
    return (TERM_COLORS['BOLD_RED'] if dirty_working_directory() else
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 359, in dirty_working_directory
    return git_dirty_working_directory() or hg_dirty_working_directory()
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 236, in wrapper
    return func(*args, **kwargs)
  File "/home/stefan/envs/py3/lib/python3.4/site-packages/xonsh/environ.py", line 349, in hg_dirty_working_directory
    id = call_hg_command(['identify', '--id'], cwd).strip(os.linesep)
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by scopatz** [comment]
Thanks @stefanv.  Just to clarify, this is from pip only, right?

**Comment by stefanv** [comment]
That's correct, yes.

**Comment by scopatz** [comment]
Is this still occurring?
