### ISSUE TITLE
API break with FORMATTER_DICT?

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#416]
I don't know why I'm just noticing this now, but my .xonshrc breaks with xonsh >= 0.2.0

```
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/xonsh", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/main.py", line 71, in main
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/shell.py", line 27, in __init__
    self._init_environ(ctx)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/shell.py", line 63, in _init_environ
    self.ctx = xonshrc_context(rcfile=rc, execer=self.execer)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/environ.py", line 622, in xonshrc_context
    execer.exec(rc, glbs=env)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 126, in exec
    return exec(code, glbs, locs)
  File "/Users/aaronmeurer/.xonshrc", line 29, in <module>
    $FORMATTER_DICT['cwd_dirname'] = cwd_dirname
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/environ.py", line 253, in __getitem__
    val = self._d[key]
KeyError: 'FORMATTER_DICT'
```

Here is my .xonshrc https://github.com/asmeurer/dotfiles/blob/abcf987c0c3cc6501ec80ec5aef2b19b976b8d1a/.xonshrc

**Comment by asmeurer** [comment]
I guess that should be >= 0.2.1.

**Comment by scopatz** [comment]
OK v0.2.2 should fix this. Sorry about the trouble. 

Also, note, it wasn't an API break per se, but I was to aggressive in removing some items from the default environment.  The critical ones are back.  Thanks for reporting!

**Comment by scopatz** [comment]
Please close this issue once you can confirm it works. Thanks again.

**Comment by asmeurer** [comment]
It is fixed.
