### ISSUE TITLE
Crash with prompt-toolkit and quotes

### ISSUE THREAD

**Issue by davidbrochart** [scopatz/xonsh#425]
When starting to type `git commit -m "..."`, I get the following error after pressing the quote key:
```
david@david-VirtualBox ~ $ git commit -m "Exception in thread Thread-50:
Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/david/anaconda3/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/anaconda3/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 624, in run
    CompleteEvent(text_inserted=True)))
  File "/home/david/anaconda3/lib/python3.4/site-packages/xonsh/prompt_toolkit_completer.py", line 30, in get_completions
    self.ctx)
  File "/home/david/anaconda3/lib/python3.4/site-packages/xonsh/completer.py", line 134, in complete
    for s in self.bash_complete(prefix, line, begidx, endidx):
  File "/home/david/anaconda3/lib/python3.4/site-packages/xonsh/completer.py", line 265, in bash_complete
    stderr=subprocess.PIPE)
  File "/home/david/anaconda3/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['bash']' returned non-zero exit status 1
```
I am using version 0.2.0 and it only happens with prompt-toolkit.

**Comment by scopatz** [comment]
Hmmm  do you not have git's bash completions installed? What happens if you set the `$BASH_COMPLETIONS` variable to an empty list in your xonshrc file and try this in a new terminal?

**Comment by davidbrochart** [comment]
You're right, that was causing the crash. Setting the `$BASH_COMPLETIONS` variable to an empty list worked.
