### ISSUE TITLE
Cannot use bash-style &&

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#431]
A common thing to do in my bash shell is

```bash
sudo apt update && sudo apt -y upgrade
```

This however yeild the continuation line `.. `. Hitting return again yields:

```bash
 $ sudo apt update && sudo apt -y upgrade
.. 
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: apt',)
```

Full stack trace:

```
Traceback (most recent call last):
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 2505, in p_error
    column=p.lexpos))
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 334, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:23: ('code: sudo',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/base_shell.py", line 158, in push
    locs=self.ctx)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/execer.py", line 94, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/execer.py", line 69, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/execer.py", line 163, in _parse_ctx_free
    raise original_error
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/path/to/my/venv/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 2505, in p_error
    column=p.lexpos))
  File "/path/to/my/venv/lib/python3.4/site-packages/xonsh/parser.py", line 334, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: apt',)
```

**Comment by scopatz** [comment]
This is a duplicate of #137. Furthermore, as discussed there, I believe that `and`, `or`, and `not`  are better choices, though I am open to a compatibility layer using `&&`.  #253 is a partial implementation that could use some love and support. This is low on my personal priority list, and so it is more than fair game to implement. Pull requests very welcome.

**Comment by eldamir** [comment]
alright, thanks :wink:
