### ISSUE TITLE
Couldn't install with pip or pip3

### ISSUE THREAD

**Issue by debugger22** [scopatz/xonsh#45]
Error with pip
```
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_root/xonsh/setup.py", line 111, in <module>
        main()
      File "/tmp/pip_build_root/xonsh/setup.py", line 46, in main
        print(logo)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/xonsh/setup.py", line 111, in <module>

    main()

  File "/tmp/pip_build_root/xonsh/setup.py", line 46, in main

    print(logo)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)
```

Error with pip3
```
Building lexer and parser tables.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/xonsh/setup.py", line 111, in <module>

    main()

  File "/tmp/pip_build_root/xonsh/setup.py", line 68, in main

    setup(**skw)

  File "/usr/lib/python3.3/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.3/distutils/dist.py", line 929, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.3/distutils/dist.py", line 948, in run_command

    cmd_obj.run()

  File "/tmp/pip_build_root/xonsh/setup.py", line 36, in run

    build_tables()

  File "/tmp/pip_build_root/xonsh/setup.py", line 28, in build_tables

    from xonsh.parser import Parser

  File "/tmp/pip_build_root/xonsh/xonsh/parser.py", line 9, in <module>

    from xonsh import ast

  File "/tmp/pip_build_root/xonsh/xonsh/ast.py", line 3, in <module>

    from ast import Module, Num, Expr, Str, Bytes, UnaryOp, UAdd, USub, Invert, \

ImportError: cannot import name NameConstant
```

**Comment by scopatz** [comment]
The pip issue looks like a Python 2 issue.  xonsh does not support Python 2 (yet).

The pip3 issue looks like you are on a version of Python < v3.4.  What version of Python 3 are you on?

**Comment by debugger22** [comment]
> The pip issue looks like a Python 2 issue. xonsh does not support Python 2 (yet).

Cool.

> The pip3 issue looks like you are on a version of Python < v3.4. What version of Python 3 are you on?

Pyhton 3.3

I have python3.4 installed too. How do I install it then?

Thanks for the help.

**Comment by scopatz** [comment]
This link should help you with specifying Python versions in pip: https://docs.python.org/3/installing/#work-with-multiple-versions-of-python-installed-in-parallel

**Comment by debugger22** [comment]
Thanks! :)
