### ISSUE TITLE
slicing along multiple axes in numpy results in parser error 

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#478]
This is definitely xonsh's fault.

```console
scopatz@localhost ~/Downloads $ z[0:-1,0]
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 158, in push
    locs=self.ctx)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 94, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 69, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 1880, in p_subscriptlist
    p1.value = ast.Tuple(elts=[p1.value] + [x.value for x in p2],
AttributeError: 'Slice' object has no attribute 'value'
```

**Comment by scopatz** [comment]
@gforsyth - you fixed this correct?

**Comment by gforsyth** [comment]
@scopatz , yep.

```console
gil@theo ~ $ import numpy
gil@theo ~ $ a = numpy.random.random((5, 5, 5))
gil@theo ~ $ a[2:,2:,2:]
array([[[ 0.98026944,  0.75864377,  0.29827613],
        [ 0.84825397,  0.55844064,  0.91752772],
        [ 0.06143154,  0.55192993,  0.19352294]],

       [[ 0.60709962,  0.32869308,  0.44706684],
        [ 0.4840777 ,  0.31217137,  0.12700196],
        [ 0.26647231,  0.90975815,  0.80857804]],

       [[ 0.30275576,  0.04680566,  0.35927849],
        [ 0.98841122,  0.72070028,  0.56742726],
        [ 0.16079333,  0.67989532,  0.9167964 ]]])
```

**Comment by scopatz** [comment]
Great! I'll close this one then :)
