### ISSUE TITLE
"module" object has no attribute '__xonsh_shell__'

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#566]
0c132528 broke xonsh for me.  

```
xonsh 
Traceback (most recent call last):
  File "/home/gil/miniconda3/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.3', 'console_scripts', 'xonsh')()
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/main.py", line 111, in main
    args = premain(argv)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/main.py", line 98, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/shell.py", line 29, in __init__
    self._init_environ(ctx)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/shell.py", line 67, in _init_environ
    self.ctx = xonshrc_context(rcfiles=rc, execer=self.execer)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/environ.py", line 687, in xonshrc_context
    execer.exec(rc, glbs=env)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "/home/gil/.xonshrc", line 8, in <module>
    evalx("keychain --quiet ~/.ssh/id_ed25519")
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/execer.py", line 113, in eval
    return eval(code, glbs, locs)
  File "/home/gil/.xonshrc", line 1, in <module>
    import os
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/built_ins.py", line 653, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "/home/gil/miniconda3/lib/python3.4/site-packages/xonsh/built_ins.py", line 618, in run_subproc
    builtins.__xonsh_shell__.settitle()
AttributeError: 'module' object has no attribute '__xonsh_shell__'
```

I have an `evalx` in my `xonshrc` to load my ssh keys and that seems to be the problem.  Removing the offending lines in `built_ins.py` lets xonsh load but, predictably, breaks the titling.

**Comment by adqm** [comment]
Sorry for the trouble, and thanks for reporting.  Can you see if #567 fixes?

**Comment by gforsyth** [comment]
That fixed it.  Thanks!
