### ISSUE TITLE
Startup (compile?) fails on Python 3.5.1

### ISSUE THREAD

**Issue by kseistrup** [scopatz/xonsh#569]
Having upgraded Python from 3.5.0 to 3.5.1 on Arch Linux I get the following traceback when trying to launch `xonsh`:

```pytb
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.3', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 111, in main
    args = premain(argv)
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 98, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.5/site-packages/xonsh/shell.py", line 29, in __init__
    self._init_environ(ctx)
  File "/usr/lib/python3.5/site-packages/xonsh/shell.py", line 67, in _init_environ
    self.ctx = xonshrc_context(rcfiles=rc, execer=self.execer)
  File "/usr/lib/python3.5/site-packages/xonsh/environ.py", line 685, in xonshrc_context
    execer.exec(rc, glbs=env)
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 124, in exec
    stacklevel=stacklevel)
  File "/usr/lib/python3.5/site-packages/xonsh/execer.py", line 98, in compile
    code = compile(tree, filename, mode)
TypeError: required field "lineno" missing from arg
```

However, I don't quite understand this error message because `compile()` doesn't seem to require a `lineno` arg:

```py
>>> help(compile)
Help on built-in function compile in module builtins:

compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1)
    Compile source into a code object that can be executed by exec() or eval().
    
    The source code may represent a Python module, statement or expression.
    The filename will be used for run-time error messages.
    The mode must be 'exec' to compile a module, 'single' to compile a
    single (interactive) statement, or 'eval' to compile an expression.
    The flags argument, if present, controls which future statements influence
    the compilation of the code.
    The dont_inherit argument, if true, stops the compilation inheriting
    the effects of any future statements in effect in the code calling
    compile; if absent or false these statements do influence the compilation,
    in addition to any features explicitly specified.
```

**Comment by adqm** [comment]
Hmmmm.  Well, I am not sure where _exactly_ it's happening, but that error message is probably actually coming from somewhere else (that is, not from passing the wrong args to `compile`).

Xonsh works by building up a Python AST, and then compiling and running that.  Many of the nodes in the AST require an argument `lineno` to let Python know what line they live on.  So I would imagine that this is a parser bug with one of the new 3.5-related things.

Maybe it is related to [this Python issue](https://bugs.python.org/25555)?  It seems that at least one thing in AST that didn't require `lineno` in 3.5 does in 3.5.1.

**Comment by adqm** [comment]
I don't have py3.5.1 to test on now.  If @scopatz doesn't swoop in to fix this, though, I'll try to find some time to get py3.5.1, patch, and test.

**Comment by kseistrup** [comment]
Cool, thanks!

**Comment by gforsyth** [comment]
Hey @kseistrup -- do you still get the error if you start `xonsh` with the `--no-rc` flag?  I have the same `lineno` error with Python 3.5.1 but only when I use `source`

**Comment by adqm** [comment]
@gforsyth, what about if you run the same commands that are in the file you are `sourcing` from the command line?  Based on my current hypothesis as to what the problem is, I would imagine that it would still break on at least one of those commands (probably a function definition or call), but it would be really useful to know if that doesn't break it!

**Comment by gforsyth** [comment]
@adqm -- oddly enough it doesn't break if I don't source it, although it doesn't do anything (since I'm not sourcing it).  It's my hacky xonsh script for selecting a different python environment 

https://github.com/gforsyth/xonshhelpers/blob/master/pyselect.xsh

**Comment by gforsyth** [comment]
for reference:

```
(xonshtesting)gil@theo~/git/xonsh master$ source pyselect
Traceback (most recent call last):
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/proc.py", line 338, in wrapped_simple_command
    r = f(args, i)
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/aliases.py", line 118, in source_alias
    execx(fp.read(), 'exec', builtins.__xonsh_ctx__)
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/execer.py", line 124, in exec
    stacklevel=stacklevel)
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/execer.py", line 98, in compile
    code = compile(tree, filename, mode)
TypeError: required field "lineno" missing from arg
```

vs

```
(xonshtesting)gil@theo~/git/xonsh master$ pyselect
0. /home/gil/anaconda
1. /home/gil/anaconda/envs/bqplot
2. /home/gil/anaconda/envs/codegen
3. /home/gil/anaconda/envs/nummooc
4. /home/gil/anaconda/envs/py3mpl15
5. /home/gil/anaconda/envs/pycuda
6. /home/gil/anaconda/envs/pygbe
7. /home/gil/anaconda/envs/xonshtesting
8. /home/gil/anaconda/envs/_build
Choose env: 
```

**Comment by kseistrup** [comment]
@gforsyth I get no errors if I run `xonsh` with the `--no-rc` flag. :smile:

**Comment by gforsyth** [comment]
@kseistrup ahh, so then the question is, what do you have in your `xonshrc`?  Any usage of `source` or something else?

**Comment by kseistrup** [comment]
Now it's getting interesting. Here's the top of my `~/.xonshrc`:

```py
# -*- mode: python; coding: utf-8 -*-

# For full traceback set: $XONSH_SHOW_TRACEBACK=True
$XONSH_SHOW_TRACEBACK=False

$AUTO_CD=True

$LANG='en_DK.UTF-8'
$LC_ALL='en_DK.UTF-8'

$LS_COLORS=r'*.do=00;35:*Makefile=00;35:*.o=00;30;1:*.pyc=00;30;1:*.pyo=00;30;1:*~=00;30;1:*.tmp=00;30;1:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:';

aliases['exec'] = aliases['xexec']

# see() is dir() for humans
try:
    from see import see
except ImportError:
    see = dir

from fractions import gcd
```

After those lines I have a few trivial methods.

The above does *not* crash `xonsh`. Neither does `xonsh` crash if I add a method that doesn't take any arguments:

```py
def crashme():
    pass
```

However, if that methoad takes an argument, `xonsh` fails:

```py
def crashme(boom):
    pass
```
:bomb:

**Comment by adqm** [comment]
> However, if that method takes an argument, xonsh fails:

Perfect!  That matches my hypothesis exactly.  I am 99% certain I know where the bug is.  Will try to fix this evening.

**Comment by kseistrup** [comment]
:+1:

**Comment by scopatz** [comment]
> Perfect! That matches my hypothesis exactly. I am 99% certain I know where the bug is. Will try to fix this evening.

Awesome :)

**Comment by adqm** [comment]
hi @kseistrup, @gforsyth, can you please test and see if #570 resolves this for you?  it worked for me on py3.5.1 and py3.4.

**Comment by kseistrup** [comment]
I don't have 3.4 installed but 3.5.1 still barfs here (I installed the adqm:351 branch) in exactly the same way as before.

**Comment by adqm** [comment]
wait, really?  hmmmm, i can't reproduce that.  for me, master fails exactly as you described, but adqm:351 works (sourcing, defining functions that take arguments, etc).

are you sure that the xonsh you are running is the updated version?

**Comment by kseistrup** [comment]
Yes, I completely deinstalled xonsh before installing adqm:351, and I just checked that this is indeed the version I attempt to launch.

**Comment by adqm** [comment]
Here's what I get:

```
hartz@lappy-511 ~/myxonsh $ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
hartz@lappy-511 ~/myxonsh $ sudo python3 setup.py install > /dev/null
hartz@lappy-511 ~/myxonsh $ xonsh -c "echo 'hi'"
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.3', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 111, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 98, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 29, in __init__
    self._init_environ(ctx)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 67, in _init_environ
    self.ctx = xonshrc_context(rcfiles=rc, execer=self.execer)
  File "/usr/local/lib/python3.5/site-packages/xonsh/environ.py", line 687, in xonshrc_context
    execer.exec(rc, glbs=env)
  File "/usr/local/lib/python3.5/site-packages/xonsh/execer.py", line 124, in exec
    stacklevel=stacklevel)
  File "/usr/local/lib/python3.5/site-packages/xonsh/execer.py", line 98, in compile
    code = compile(tree, filename, mode)
TypeError: required field "lineno" missing from arg
hartz@lappy-511 ~/myxonsh $ git checkout 351
Switched to branch '351'
hartz@lappy-511 ~/myxonsh $ sudo python3 setup.py install > /dev/null
hartz@lappy-511 ~/myxonsh $ xonsh -c "echo 'hi'"
hi
```

**Comment by adqm** [comment]
okay, maybe there are other changes needed beyond the ones i made.

can you please try starting with `--no-rc` again, and running your "`crashme`" examples?

**Comment by kseistrup** [comment]
Yes, hang on…

**Comment by kseistrup** [comment]
Does it work on 3.5.1 if you add these two methods to `~/.xonshrc`:

```py
# °F → °C
f2c = lambda f: (f - 32) * 5 / 9
# °C → °F
c2f = lambda c: c * 9 / 5 + 32
```

?

**Comment by adqm** [comment]
Yep, that broke it.  Just pushed something to adqm:351 that I think should fix?

**Comment by adqm** [comment]
_Of course_ `lambda` args are in a different place than `def` args... :)

**Comment by kseistrup** [comment]
It works with my `~/.xonshrc` now. Fantastic! :smile:

**Comment by gforsyth** [comment]
Fixes my `source` problem, but it also triggers the `__xonsh_shell__` error from #566.

Ahh, but I see that that's just because your fix isn't rolled into this branch.  Ok.  All good on my end!

**Comment by scopatz** [comment]
Thanks everybody!  Feel free to close...

**Comment by kseistrup** [comment]
It's fine here, @gforsyth?

**Comment by gforsyth** [comment]
Close away.

**Comment by kseistrup** [comment]
:+1:
