### ISSUE TITLE
Crash on parsing list nested in dict

### ISSUE THREAD

**Issue by mbollmann** [scopatz/xonsh#61]
When parsing a line containing a dict that has a list (or tuple) as a value, xonsh crashes.

```
bollmann@underberg ~/repositories/xonsh master >>> {'foo': ['a', 'b']}
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/bollmann/repositories/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/bollmann/repositories/xonsh/xonsh/main.py", line 25, in main
    shell.cmdloop()
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 152, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.4/cmd.py", line 211, in onecmd
    return self.default(line)
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 105, in default
    code = self.push(line)
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 126, in push
    locs=self.ctx)
  File "/home/bollmann/repositories/xonsh/xonsh/execer.py", line 87, in compile
    code = compile(tree, self.filename, mode)
ValueError: Dict doesn't have the same number of keys as values
bollmann@underberg ~/repositories/xonsh (master) $ 
```

Other nested structures seem to work fine. Putting the list in a variable first and then constructing the dict also works fine.

```
bollmann@underberg ~/repositories/xonsh master >>> x = ['a', 'b']
bollmann@underberg ~/repositories/xonsh master >>> {'foo': x}
{'foo': ['a', 'b']}
bollmann@underberg ~/repositories/xonsh master >>> {'a': {'b': 'c', 'd': 'e'}}
{'a': {'b': 'c', 'd': 'e'}}
bollmann@underberg ~/repositories/xonsh master >>> [{'a': 'b', 'c': 'd'}]
[{'a': 'b', 'c': 'd'}]
bollmann@underberg ~/repositories/xonsh master >>> [{'a': 'b'}, {'c': 'd'}]
[{'a': 'b'}, {'c': 'd'}]
bollmann@underberg ~/repositories/xonsh master >>> {'a': {'b': 'c', 'd': 'e'}}
{'a': {'b': 'c', 'd': 'e'}}
```

**Comment by scopatz** [comment]
Thanks for reporting @mbollmann!

**Comment by scopatz** [comment]
Hey @mbollmann, I have put in #100. If you could take a look at that branch and let me know if it works for you, that'd be great! thanks.

**Comment by mbollmann** [comment]
Fixes the cases that I described above, but still doesn't get everything right as mentioned here:
https://github.com/scopatz/xonsh/pull/100#issuecomment-83510570

(I'm duplicating this info here since I got confused myself that I supposedly hadn't answered this yet...)

**Comment by mbollmann** [comment]
Nevermind, just saw there is a separate issue for that problem.

The specific bug described here is fixed. Closing.
