### ISSUE TITLE
Can't run tests from xonsh in Git CMD

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#689]
I cloned the repo and trying to run the tests. This might just be a documentation change. 

https://github.com/scopatz/xonsh/blame/master/docs/devguide.rst#L85

I'm also wondering why ```Scripts``` appears in the list of suggestions after pressing ```TAB```.(I added the ```<TAB>``` in the code block)

```shell
Cody@Codetop ~\Desktop\xonsh master $ Script<TAB>
Scripts      scripto.dll  scripts\
Cody@Codetop ~\Desktop\xonsh master $ Scripts<TAB>
Scripts  scripts\
Cody@Codetop ~\Desktop\xonsh master $ scripts\run_tests.xsh
C:\Users\Cody\Desktop\xonsh\xonsh\shell.py:82: UserWarning: prompt_toolkit is not available, using readline instead.
  warn('prompt_toolkit is not available, using readline instead.')
Traceback (most recent call last):
  File "C:\Users\Cody\Desktop\xonsh\xonsh\built_ins.py", line 587, in run_subproc
    **subproc_kwargs)
  File "C:\Users\Cody\Anaconda3\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Cody\Anaconda3\lib\subprocess.py", line 1114, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cody\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Cody\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cody\Desktop\xonsh\xonsh\main.py", line 222, in <module>
    main()
  File "C:\Users\Cody\Desktop\xonsh\xonsh\main.py", line 182, in main
    shell.execer.exec(code, mode='exec', glbs=shell.ctx)
  File "C:\Users\Cody\Desktop\xonsh\xonsh\execer.py", line 126, in exec
    return exec(code, glbs, locs)
  File "scripts\run_tests.xsh", line 22, in <module>
    $[make build-tables] # ensure lexer/parser table module is up to date
  File "C:\Users\Cody\Desktop\xonsh\xonsh\built_ins.py", line 655, in subproc_uncaptured
    return run_subproc(cmds, captured=False)
  File "C:\Users\Cody\Desktop\xonsh\xonsh\built_ins.py", line 597, in run_subproc
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: make
Did you mean the following?
    move:  Alias
Cody@Codetop ~\Desktop\xonsh master $
```

When I run ```python3 -c import setup; setup.build_tables() $ env XONSHRC= nosetests``` it hangs until I press enter and there is an error.
```shell
Cody@Codetop ~\Desktop\xonsh master $ python3 -c import setup; setup.build_tables() $ env XONSHRC= nosetests
.....................................
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: <xonsh-code>:1:11: ('code: import',)
Cody@Codetop ~\Desktop\xonsh master $ python --version
Python 3.4.4 :: Anaconda 2.3.0 (32-bit)
Cody@Codetop ~\Desktop\xonsh master $
```

**Comment by scopatz** [comment]
hmm I kinda don't like that Make script stuff.  I think we should probably remove it. To run the tests you can always run `nosetests` from the root directory, though you probably want to run `nosetests -q` to prevent an excess of dots.

**Comment by Siecje** [comment]
```nosetests -q``` works

**Comment by scopatz** [comment]
Great! I think that once #690 is merged, you should feel free to close this.

**Comment by scopatz** [comment]
#690 has been merged, please feel free to close @Siecje
