### ISSUE TITLE
NoneType has no attribute lines

### ISSUE THREAD

**Issue by Carreau** [scopatz/xonsh#756]
Huge CrashBacks, I'm not sure how I got on 95796f26db12252bd25193cbd1808453b32a82a9, while doing something, but not sure what... Probably pressing Ctrl-C or Ctrl-D. Not sure how to reproduce, so just posting that there just in case. 

```
$ Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 353, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 150, in run
    t()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 293, in redraw
    self._redraw()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 313, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/renderer.py", line 420, in render
    extended_height=size.rows,
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 141, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 176, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 176, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 174, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 394, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 971, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 478, in preferred_height
    content = self.create_content(cli, width, None)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 615, in create_content
    line_count=document.line_count,
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/document.py", line 166, in line_count
    return len(self.lines)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/document.py", line 122, in lines
    if self._cache.lines is None:
AttributeError: 'NoneType' object has no attribute 'lines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh', 'console_scripts', 'xonsh')()
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/main.py", line 214, in main
    shell.cmdloop()
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/ptk/shell.py", line 112, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/ptk/shell.py", line 81, in singleline
    display_completions_in_columns=multicolumn)
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/ptk/shortcuts.py", line 102, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 363, in run
    self._redraw()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 313, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/renderer.py", line 420, in render
    extended_height=size.rows,
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 141, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 176, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 176, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 174, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 394, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 971, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 478, in preferred_height
    content = self.create_content(cli, width, None)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 615, in create_content
    line_count=document.line_count,
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/document.py", line 166, in line_count
    return len(self.lines)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/document.py", line 122, in lines
    if self._cache.lines is None:
AttributeError: 'NoneType' object has no attribute 'lines'
d
```

**Comment by scopatz** [comment]
Is this still happening @Carreau? Did you ever find a way to reproduce this?

**Comment by Carreau** [comment]
Have not seen that in while. I can reopen if necessary, and if I see it again.

**Comment by scopatz** [comment]
Thanks @Carreau
