### ISSUE TITLE
Clean up tests (again)

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#758]
I must admit that I have kind of ignored running the xonsh test suite for a while. Trying it again now, made me remember why. 

Firstly, the test script doesn't work on Windows. That may be less of a problem, but we @BYK and I ought to fix it at some point. 

The partial string test https://github.com/scopatz/xonsh/blob/master/tests/test_tools.py#L304 generate too many test cases (many thousands) . I didn't think it was a big deal when @adqm did the PR, but it scares new contributors away. I don't think it is necessary to test all combinations. 

Lastly, I get some errors when running tests which I can't fix. Maybe @scopatz can figure out what is going on. 

```
C:\Users\mel\Documents\xonsh>nosetests -q
C:\Users\mel\Anaconda3\lib\site-packages\win_unicode_console\__init__.py:27: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == None, readline hook consumer may assume they are the same
  readline_hook.enable(use_pyreadline=use_pyreadline)
WARNING: Token 'AT' multiply defined
Generating LALR tables
WARNING: 92 shift/reduce conflicts
WARNING: 9 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 110 resolved using rule (test_or_star_expr -> test)
WARNING: rejected rule (testlist -> test) in state 110
WARNING: reduce/reduce conflict in state 185 resolved using rule (string_tok -> STRING)
WARNING: rejected rule (subproc_arg_part -> STRING) in state 185
WARNING: reduce/reduce conflict in state 273 resolved using rule (test_or_star_expr -> test)
WARNING: rejected rule (testlist -> test) in state 273
======================================================================
ERROR: Failure: JSONDecodeError (Expecting ',' delimiter: line 1 column 3708 (char 3707))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 44, in test_echo
    with a_replay(f) as hist:
  File "C:\Users\mel\Anaconda3\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 36, in a_replay
    hist = run_replay(re_file)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 22, in run_replay
    r = Replayer(re_file)
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 29, in __init__
    self._lj = lazyjson.LazyJSON(f, reopen=reopen)
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 212, in __init__
    self._load_index()
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 245, in _load_index
    idx = json.loads(idx)
  File "C:\Users\mel\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 3708 (char 3707)

======================================================================
ERROR: Failure: JSONDecodeError (Expecting ',' delimiter: line 1 column 3708 (char 3707))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 51, in test_reecho
    with a_replay(f) as hist:
  File "C:\Users\mel\Anaconda3\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 36, in a_replay
    hist = run_replay(re_file)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 22, in run_replay
    r = Replayer(re_file)
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 29, in __init__
    self._lj = lazyjson.LazyJSON(f, reopen=reopen)
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 212, in __init__
    self._load_index()
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 245, in _load_index
    idx = json.loads(idx)
  File "C:\Users\mel\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 3708 (char 3707)

======================================================================
ERROR: Failure: JSONDecodeError (Expecting ',' delimiter: line 1 column 3965 (char 3964))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 58, in test_simple_python
    with a_replay(f) as hist:
  File "C:\Users\mel\Anaconda3\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 36, in a_replay
    hist = run_replay(re_file)
  File "C:\Users\mel\Documents\xonsh\tests\test_replay.py", line 22, in run_replay
    r = Replayer(re_file)
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 29, in __init__
    self._lj = lazyjson.LazyJSON(f, reopen=reopen)
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 212, in __init__
    self._load_index()
  File "C:\Users\mel\Documents\xonsh\xonsh\lazyjson.py", line 245, in _load_index
    idx = json.loads(idx)
  File "C:\Users\mel\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mel\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 3965 (char 3964)

----------------------------------------------------------------------
Ran 132549 tests in 37.161s

FAILED (SKIP=8, errors=3)
Exception ignored in: <bound method Replayer.__del__ of <xonsh.replay.Replayer object at 0x000002527C657668>>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 32, in __del__
    self._lj.close()
AttributeError: 'Replayer' object has no attribute '_lj'
Exception ignored in: <bound method Replayer.__del__ of <xonsh.replay.Replayer object at 0x000002527C89E2E8>>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 32, in __del__
    self._lj.close()
AttributeError: 'Replayer' object has no attribute '_lj'
Exception ignored in: <bound method Replayer.__del__ of <xonsh.replay.Replayer object at 0x000002527C89EF28>>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\replay.py", line 32, in __del__
    self._lj.close()
AttributeError: 'Replayer' object has no attribute '_lj'
```

**Comment by BYK** [comment]
Tests pass for me locally without any issues. That said I'm willing to help maintain/fix tests for Windows.

**Comment by melund** [comment]
Do you use the test script or do you run the tests manually

**Comment by BYK** [comment]
I ran `nosetests -q` as you suggested in this ticket.

**Comment by melund** [comment]
Maybe I have some old history files that cause problems. Or maybe it is because xonsh is installed in developer mode. I have no clue what the error is caused by.

**Comment by BYK** [comment]
@melund - My bet is old history files.

**Comment by melund** [comment]
Finally figured what was causing the test failures:  `git config --global core.autocrlf true`... Made a PR to fix it https://github.com/scopatz/xonsh/pull/760

**Comment by scopatz** [comment]
Is this closable now @melund?

**Comment by melund** [comment]
Yes. I will close. 

But I still think we should reduce the number of tests by simplifying https://github.com/scopatz/xonsh/blob/master/tests/test_tools.py#L304 But I think it up to @adqm to judge which of the combinations are still necessary to test.
