### ISSUE TITLE
Running a script with tracer fails

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#782]
I tried to run a script with the tracer set, but I get the following error: 

```
C:\Users\mel\Documents\scrats>xonsh test.xsh
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\xonsh-script.py", line 9, in <module>
    load_entry_point('xonsh', 'console_scripts', 'xonsh')()
  File "c:\users\mel\documents\xonsh\xonsh\main.py", line 218, in main
    shell.execer.exec(code, mode='exec', glbs=shell.ctx)
  File "c:\users\mel\documents\xonsh\xonsh\execer.py", line 124, in exec
    return exec(code, glbs, locs)
  File "test.xsh", line 2, in <module>
    `.*.py`
  File "test.xsh", line 2, in <module>
    `.*.py`
  File "c:\users\mel\documents\xonsh\xonsh\tracer.py", line 80, in trace
    lexer=self.lexer, formatter=self.formatter)
  File "c:\users\mel\documents\xonsh\xonsh\tracer.py", line 96, in format_line
    fname = min(fname, replace_home(fname), os.path.relpath(fname), key=len)
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 947, in _replace_home
    home = (builtins.__xonsh_env__['HOMEDRIVE'] +
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 617, in __getitem__
    raise KeyError(e.format(key))
KeyError: 'Unknown environment variable: $HOMEDRIVE'
```

It seems like all the environment variables (not xonsh' own) are not set when running scripts.

**Comment by adqm** [comment]
Ah, right.  I probably went too far with this.  As a temporary workaround, does it work if you run xonsh with the `--login` option?

**Comment by melund** [comment]
@adqm ...  No. It doesn't seem to be a workaround: 

```
C:\Users\mel\Documents\scrats>xonsh --login test.xsh
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\xonsh-script.py", line 9, in <module>
    load_entry_point('xonsh', 'console_scripts', 'xonsh')()
  File "c:\users\mel\documents\xonsh\xonsh\main.py", line 218, in main
    shell.execer.exec(code, mode='exec', glbs=shell.ctx)
  File "c:\users\mel\documents\xonsh\xonsh\execer.py", line 124, in exec
    return exec(code, glbs, locs)
  File "test.xsh", line 2, in <module>
    `.*.py`
  File "test.xsh", line 2, in <module>
    `.*.py`
  File "c:\users\mel\documents\xonsh\xonsh\tracer.py", line 80, in trace
    lexer=self.lexer, formatter=self.formatter)
  File "c:\users\mel\documents\xonsh\xonsh\tracer.py", line 96, in format_line
    fname = min(fname, replace_home(fname), os.path.relpath(fname), key=len)
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 947, in _replace_home
    home = (builtins.__xonsh_env__['HOMEDRIVE'] +
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 617, in __getitem__
    raise KeyError(e.format(key))
KeyError: 'Unknown environment variable: $HOMEDRIVE'
```

**Comment by scopatz** [comment]
Thanks for reporting @melund.  We should probably have a test that makes sure that `_replace_home()` works even if $HOMEDRIVE is not set.

**Comment by melund** [comment]
Yes. But it is not only $HOMEDRIVE that is missing. None of the system environment variables are loaded when running xonsh scripts. Is that intended?

**Comment by scopatz** [comment]
by system, do you mean that it isn't inheriting any of the environment of parent process?

**Comment by scopatz** [comment]
Hmm, looking at the code, it seems like it should get this envvars.  Can you `print(${...})` in the script to check?

**Comment by melund** [comment]
Well. I thought that it didn't inherit any, but there are few. Adding `print(${...])` to the script gives me this. 
```
{'TMP': 'C:\\Users\\mel\\AppData\\Local\\Temp',
 'PWD': 'C:\\Users\\mel\\Documents\\scrats',
 'XONSH_INTERACTIVE': False,
 'PROMPT': '{env_name}{BOLD_INTENSE_GREEN}{user}@{hostname}{BOLD_INTENSE_CYAN} {cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_INTENSE_CYAN}{prompt_end}{NO_COLOR} ',
 'SHELL_TYPE': 'none',
 'PATH': ['C:\\Users\\mel\\Anaconda3\\Library\\bin', .... 'C:\\Program Files\\Docker Toolbox'],
 'TEMP': 'C:\\Users\\mel\\AppData\\Local\\Temp',
 'XONSH_LOGIN': False,
 'ARGS': ['test.xsh']}
```

**Comment by melund** [comment]
@scopatz. I was wrong about runing the script in `login` mode not beeing a workaround. I just assumed that `xonsh --login script.xsh` was valid. It should have been ´xonsh -l script.xsh` 

So running with in login mode is a workaround as @adqm suggested.

**Comment by scopatz** [comment]
Ahh maybe we need to add `--login` as an option then :)
