### ISSUE TITLE
breaking?

### ISSUE THREAD

**Issue by SolarAquarion** [scopatz/xonsh#784]
```console
%f%b%k%K{black} %F{011}solaraquarion@%m %K{blue}%F{black} %F{black}%~ %k%F{blue
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 236, in main
    shell.cmdloop()
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 111, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 80, in singleline
    display_completions_in_columns=multicolumn)
  File "/usr/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 104, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 366, in run
    with self.input.raw_mode():
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 415, in __enter__
    os.write(self.fileno, b'\x1b[?1l')
OSError: [Errno 9] Bad file descriptor
```

**Comment by scopatz** [comment]
Hi @SolarAquarion, thanks for reporting.  I believe that this is a bug with prompt-toolkit given where the error is coming from.  But just to be sure, what is the output of the `xonfig` command?  Also, does using the readline shell work?
