### ISSUE TITLE
Incorrect prompt, cannot run commands, when inside a directory without read privileges

### ISSUE THREAD

**Issue by Lunderberg** [scopatz/xonsh#838]
When inside a directory for which the current user does not have read privileges, a PermissionError is thrown after each command, and the prompt is incorrectly formatted.  While in such a directory, no subprocesses can be started.

Expected behavior:

```
myusername@myhostname ~ $ mkdir test
myusername@myhostname ~ $ cd test
myusername@myhostname ~/test $ ls
myusername@myhostname ~/test $ chmod u-r .
myusername@myhostname ~/test $ ls
PermissionError: [Errno 13] Permission denied: '.'
myusername@myhostname ~/test $ echo hi
hi
myusername@myhostname ~/test $ cd ~
myusername@myhostname ~ $
```

Actual behavior:

```
myusername@myhostname ~ $ cd test
myusername@myhostname ~/test $ ls
myusername@myhostname ~/test $ chmod u-r .
PermissionError: [Errno 13] Permission denied: '.'
{env_name}{user}@{hostname} {cwd}{branch_color}{curr_branch} {prompt_end} ls
PermissionError: [Errno 13] Permission denied: '.'
PermissionError: [Errno 13] Permission denied: '.'
{env_name}{user}@{hostname} {cwd}{branch_color}{curr_branch} {prompt_end} echo hi
PermissionError: [Errno 13] Permission denied: '.'
PermissionError: [Errno 13] Permission denied: '.'
{env_name}{user}@{hostname} {cwd}{branch_color}{curr_branch} {prompt_end} cd ~
myusername@myhostname ~ $
```

This is using the latest version from PyPI, `xonsh/0.2.7`, and python3.4, running on Debian 8.4.

**Comment by melund** [comment]
I can confirm this. It is the git/hg branch stuff in the prompt that is causing the error on every prompt.

**Comment by melund** [comment]
if you set `$XONSH_SHOW_TRACEBACK=True` then you should be able to see what produces the error. For me on Win it is caused by the 'locate_binary()' function. 
```
$ echo hi
Traceback (most recent call last):
  File "c:\users\mel\documents\xonsh\xonsh\base_shell.py", line 151, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "c:\users\mel\documents\xonsh\xonsh\execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "c:\users\mel\documents\xonsh\xonsh\built_ins.py", line 615, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "c:\users\mel\documents\xonsh\xonsh\built_ins.py", line 459, in run_subproc
    n = locate_binary(cmd[0])
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 751, in locate_binary
    directory in directories if os.path.isdir(directory)))
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 719, in yield_executables_windows
    for a_file in os.listdir(directory):
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\mel\\Local Settings'
```
It probably need a `try-except` block or check if it is allowed to run `os.listdir()`

**Comment by melund** [comment]
@Lunderberg Can you test if this fixes your problem? https://github.com/scopatz/xonsh/pull/841

**Comment by Lunderberg** [comment]
Tested with #841, and the issue is fixed.

**Comment by scopatz** [comment]
Thanks for reporting @Lunderberg!
