### ISSUE TITLE
which failing all the time

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#868]
Any idea why I would get this ? 

```
$ which
AttributeError: 'module' object has no attribute 'run'
```

**Comment by scopatz** [comment]
This is because the subprocess.run() function wasn't added until Python 3.5 and you are probably on v3.4. We should update the which alias to use `subprocess.check_output()` or find a way to backport run()

**Comment by scopatz** [comment]
Thanks to @gforsyth this should be fixed on master.  Would you mind testing this out please @GuillaumeLeclerc and then closing this issue? Thanks!

**Comment by gforsyth** [comment]
@scopatz @Carreau can either of you tell me which `which` command you ran that threw the error?

**Comment by scopatz** [comment]
`which -v`, `which ls`, etc. I get the following:

```console
scopatz@localhost ~ $ which -v
Illegal option -v
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/proc.py", line 335, in wrapped_simple_command
    r = f(args, i)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/aliases.py", line 369, in which
    version='{}'.format(which_version()))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/aliases.py", line 336, in which_version
    _ver = subprocess.check_output(['which','-v'])
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', '-v']' returned non-zero exit status 2
scopatz@localhost ~ $ which ls
Illegal option -v
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/proc.py", line 335, in wrapped_simple_command
    r = f(args, i)
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/aliases.py", line 369, in which
    version='{}'.format(which_version()))
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/aliases.py", line 336, in which_version
    _ver = subprocess.check_output(['which','-v'])
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', '-v']' returned non-zero exit status 2
```

**Comment by GuillaumeLeclerc** [comment]
```
$ which echo
Illegal option -v
subprocess.CalledProcessError: Command '['which', '-v']' returned non-zero exit status 2
```

**Comment by scopatz** [comment]
That doesn't seem right that `which -v` will be called what running `which ls`

**Comment by ngoldbaum** [comment]
Using the which that ships with OSX, I get

```
$ which ls
subprocess.CalledProcessError: Command '['which']' returned non-zero exit status 1
```

**Comment by scopatz** [comment]
@ngoldbaum - `which` I think means we can uniquely identify the user's OS by exit code :)

**Comment by Carreau** [comment]
which alone:
```
(rootenv)~/dev/xonsh master$ which
subprocess.CalledProcessError: Command '['which']' returned non-zero exit status 1
```

**Comment by Carreau** [comment]
check_output return `stdout`, and we need to check sterr.

**Comment by scopatz** [comment]
Closing this now, due to @gforsyth's PR.  Please feel free to reopen if needed.
