### ISSUE TITLE
Symbol not found: rl_completion_suppress_append

### ISSUE THREAD

**Issue by dahlia** [scopatz/xonsh#9]
```console
$ xonsh 
Traceback (most recent call last):
  File "~/.local/bin/xonsh", line 3, in <module>
    main()
  File "~/.local/venvs/xonsh/lib/python3.4/site-packages/xonsh/main.py", line 14, in main
    shell = Shell()
  File "~/.local/venvs/xonsh/lib/python3.4/site-packages/xonsh/shell.py", line 76, in __init__
    setup_readline()
  File "~/.local/venvs/xonsh/lib/python3.4/site-packages/xonsh/shell.py", line 30, in setup_readline
    'rl_completion_suppress_append')
ValueError: dlsym(0x1007a7a30, rl_completion_suppress_append): symbol not found

$ nm ~/.local/venvs/xonsh/lib/python3.4/lib-dynload/readline.so
00000000000024e6 s  stub helpers
                 U _PyArg_ParseTuple
                 U _PyBytes_AsString
                 U _PyCallable_Check
                 U _PyErr_CheckSignals
                 U _PyErr_Clear
                 U _PyErr_Format
                 U _PyErr_NoMemory
                 U _PyErr_Occurred
                 U _PyErr_SetFromErrno
                 U _PyErr_SetString
                 U _PyEval_RestoreThread
                 U _PyEval_SaveThread
                 U _PyExc_IOError
                 U _PyExc_TypeError
                 U _PyExc_ValueError
                 U _PyGILState_Ensure
                 U _PyGILState_Release
0000000000001690 T _PyInit_readline
                 U _PyList_New
                 U _PyList_SetItem
                 U _PyLong_AsLong
                 U _PyLong_FromLong
                 U _PyMem_Free
                 U _PyMem_Malloc
                 U _PyMem_RawMalloc
                 U _PyModule_Create2
                 U _PyModule_GetState
                 U _PyOS_InputHook
                 U _PyOS_ReadlineFunctionPointer
                 U _PyOS_snprintf
                 U _PyObject_CallFunction
                 U _PyState_FindModule
                 U _PyUnicode_AsUTF8
                 U _PyUnicode_FSConverter
                 U _PyUnicode_FromString
                 U _Py_FatalError
                 U __PyOS_ReadlineTState
                 U __Py_NoneStruct
                 U ___error
                 U ___stack_chk_fail
                 U ___stack_chk_guard
0000000000003714 d __history_length
0000000000000000 t __mh_bundle_header
                 U _add_history
0000000000001bf0 t _call_readline
                 U _clear_history
0000000000004290 b _completed_input_string
0000000000004288 b _completer_word_break_characters
0000000000003e78 d _doc_add_history
0000000000004240 d _doc_clear_history
0000000000003d70 d _doc_get_begidx
0000000000003cd8 d _doc_get_completer
0000000000003f78 d _doc_get_completer_delims
0000000000003d20 d _doc_get_completion_type
0000000000003a68 d _doc_get_current_history_length
0000000000003dc8 d _doc_get_endidx
0000000000003a10 d _doc_get_history_item
00000000000037b8 d _doc_get_line_buffer
0000000000003808 d _doc_insert_text
0000000000003718 d _doc_module
00000000000036c8 d _doc_module_le
0000000000003760 d _doc_parse_and_bind
0000000000003938 d _doc_read_history_file
00000000000038b8 d _doc_read_init_file
0000000000003848 d _doc_redisplay
0000000000003eb8 d _doc_remove_history
0000000000003f08 d _doc_replace_history
0000000000003be0 d _doc_set_completer
0000000000003e18 d _doc_set_completer_delims
0000000000003fd0 d _doc_set_completion_display_matches_hook
0000000000004160 d _doc_set_pre_input_hook
00000000000040b8 d _doc_set_startup_hook
00000000000039a0 d _doc_write_history_file
                 U _emacs_meta_keymap
                 U _fileno
00000000000018c0 t _flex_complete
                 U _free
0000000000000ad0 t _get_begidx
0000000000000a20 t _get_completer
0000000000000df0 t _get_completer_delims
0000000000001210 t _get_completion_type
0000000000001250 t _get_current_history_length
0000000000000a90 t _get_endidx
0000000000001b40 t _get_history_item
0000000000001230 t _get_history_length
0000000000003b70 d _get_history_length_doc
0000000000000dd0 t _get_line_buffer
                 U _history_get
                 U _history_get_history_state
                 U _history_truncate_file
00000000000015c0 t _insert_text
0000000000004284 b _libedit_history_start
0000000000002311 s _libedit_version_tag
                 U _memset
0000000000001a00 t _on_completion
0000000000000e90 t _on_completion_display_matches_hook
0000000000000e10 t _on_hook
0000000000001000 t _on_pre_input_hook
0000000000001050 t _on_startup_hook
0000000000001600 t _parse_and_bind
0000000000001150 t _py_add_history
0000000000000a00 t _py_clear_history
00000000000010a0 t _py_remove_history
0000000000001ee0 t _py_replace_history
                 U _read_history
00000000000013c0 t _read_history_file
00000000000014b0 t _read_init_file
00000000000008b0 t _readline_clear
00000000000009f0 t _readline_free
0000000000003380 d _readline_methods
00000000000007f0 t _readline_traverse
0000000000003300 d _readlinemodule
00000000000015a0 t _redisplay
                 U _remove_history
                 U _replace_history_entry
                 U _rl_attempted_completion_function
                 U _rl_attempted_completion_over
                 U _rl_bind_key
                 U _rl_bind_key_in_map
                 U _rl_callback_handler_install
                 U _rl_callback_handler_remove
                 U _rl_callback_read_char
                 U _rl_cleanup_after_signal
                 U _rl_complete
                 U _rl_completer_word_break_characters
                 U _rl_completion_append_character
                 U _rl_completion_display_matches_hook
                 U _rl_completion_matches
                 U _rl_completion_type
                 U _rl_free_line_state
                 U _rl_initialize
                 U _rl_insert
                 U _rl_insert_text
                 U _rl_instream
                 U _rl_library_version
                 U _rl_line_buffer
                 U _rl_outstream
                 U _rl_parse_and_bind
                 U _rl_pre_input_hook
                 U _rl_prep_terminal
                 U _rl_read_init_file
                 U _rl_readline_name
                 U _rl_redisplay
                 U _rl_startup_hook
0000000000001b20 t _rlhandler
                 U _select$DARWIN_EXTSN
0000000000000ca0 t _set_completer
0000000000001190 t _set_completer_delims
0000000000000d60 t _set_completion_display_matches_hook
0000000000000b10 t _set_history_length
0000000000003ac8 d _set_history_length_doc
0000000000000b60 t _set_hook
0000000000000ce0 t _set_pre_input_hook
0000000000000d20 t _set_startup_hook
                 U _setlocale
                 U _strcmp
                 U _strcpy
                 U _strdup
                 U _strlen
                 U _strncmp
                 U _strncpy
                 U _using_history
0000000000004280 b _using_libedit_emulation
                 U _write_history
0000000000001280 t _write_history_file
                 U dyld_stub_binder
```

**Comment by scopatz** [comment]
Are you on a mac, out of curiosity?

**Comment by dahlia** [comment]
Yes, I’m on Mac.

```console
$ uname -a
Darwin Hongs-MacBook-Pro-at-Spoqa.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin
```

**Comment by scopatz** [comment]
Hi @dahlia - I have a potential fix on my 'rl' branch.  Are you able to test it out?

**Comment by dahlia** [comment]
It still raise the same error, but with different traceback:

```pytb
Traceback (most recent call last):
  File "/.../xonsh/xonsh/shell.py", line 31, in setup_readline
    'rl_completion_suppress_append')
ValueError: dlsym(0x1004ec5b0, rl_completion_suppress_append): symbol not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dahlia/.local/bin/xonsh", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/.../xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/.../xonsh/xonsh/main.py", line 14, in main
    shell = Shell()
  File "/.../xonsh/xonsh/shell.py", line 82, in __init__
    setup_readline()
  File "/.../xonsh/xonsh/shell.py", line 36, in setup_readline
    'rl_completion_suppress_append')
ValueError: dlsym(0x1004fa680, rl_completion_suppress_append): symbol not found
```

**Comment by scopatz** [comment]
Hmm have you ever done a `pip install gnureadline`?

**Comment by scopatz** [comment]
It seems like you have a version of readline installed that is incompatible with certain tab completion features.

**Comment by dahlia** [comment]
No, I haven’t installed `gnureadline`.  Isn’t it an optional dependency?

**Comment by scopatz** [comment]
It shouldn't be a dependency at all.  However, the readline that come with your Python seems to have been mis-compiled.  How did you install Python on your machine?  Installing `pip install gnureadline` might help. If you could try and let me know, that'd be great!

**Comment by dahlia** [comment]
> How did you install Python on your machine?

I installed it using official Mac OS X 64-bit/32-bit installer distributed by python.org website.  Its version is [3.4.2][].

I think we’d better add some workaround code for it if it’s a bug of official binary.

[3.4.2]: https://www.python.org/downloads/release/python-342/

**Comment by scopatz** [comment]
I agree, we'll need to have a work around. I don't think it will be that hard.

**Comment by scopatz** [comment]
Sorry for taking so long, 10e5147 should fix the issue. Can you confirm that it does?

**Comment by dahlia** [comment]
Now it does work well.  Thanks!

**Comment by scopatz** [comment]
Great!
