### ISSUE TITLE
Test errors on Windows

### ISSUE THREAD

**Issue by mwiebe** [scopatz/xonsh#993]
Latest master, installed, then ran the tests like this:
```
C:\Dev\xonsh>nosetests > testresults.txt 2>&1
```
[testresults.txt](https://github.com/scopatz/xonsh/files/276826/testresults.txt)

```
======================================================================
ERROR: test_environ.test_load_static_config_works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_environ.py", line 118, in test_load_static_config_works
    check_load_static_config(s, {'best': 'awash'}, True)
  File "C:\Dev\xonsh\tests\test_environ.py", line 112, in check_load_static_config
    conf = load_static_config(env, f.name)
  File "C:\Dev\xonsh\xonsh\environ.py", line 1194, in load_static_config
    with open(config, 'r', encoding=encoding, errors=errors) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mwiebe\\AppData\\Local\\Temp\\tmpbc82lfra'

======================================================================
ERROR: test_environ.test_load_static_config_type_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_environ.py", line 122, in test_load_static_config_type_fail
    check_load_static_config(s, {}, False)
  File "C:\Dev\xonsh\tests\test_environ.py", line 112, in check_load_static_config
    conf = load_static_config(env, f.name)
  File "C:\Dev\xonsh\xonsh\environ.py", line 1194, in load_static_config
    with open(config, 'r', encoding=encoding, errors=errors) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mwiebe\\AppData\\Local\\Temp\\tmpuebaooej'

======================================================================
ERROR: test_environ.test_load_static_config_json_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_environ.py", line 126, in test_load_static_config_json_fail
    check_load_static_config(s, {}, False)
  File "C:\Dev\xonsh\tests\test_environ.py", line 112, in check_load_static_config
    conf = load_static_config(env, f.name)
  File "C:\Dev\xonsh\xonsh\environ.py", line 1194, in load_static_config
    with open(config, 'r', encoding=encoding, errors=errors) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mwiebe\\AppData\\Local\\Temp\\tmpum43n5wq'

======================================================================
ERROR: test suite for <module 'test_execer' from 'C:\\Dev\\xonsh\\tests\\test_execer.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\suite.py", line 210, in run
    self.setUp()
  File "C:\Anaconda3\lib\site-packages\nose\suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "C:\Anaconda3\lib\site-packages\nose\suite.py", line 316, in setupContext
    try_run(context, names)
  File "C:\Anaconda3\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\Dev\xonsh\tests\test_execer.py", line 25, in setup
    EXECER = Execer(debug_level=DEBUG_LEVEL)
  File "C:\Dev\xonsh\xonsh\execer.py", line 44, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "C:\Dev\xonsh\xonsh\built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "C:\Dev\xonsh\xonsh\environ.py", line 1272, in default_env
    issue_warning=False)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 502, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 241, in foreign_shell_data
    currenv = builtins.__xonsh_env__.detype()
AttributeError: 'dict' object has no attribute 'detype'

======================================================================
ERROR: test_imphooks.test_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_imphooks.py", line 29, in test_import
    import sample
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 79, in get_code
    execer = self.execer
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 30, in execer
    self._execer = execer = Execer(unload=False)
  File "C:\Dev\xonsh\xonsh\execer.py", line 44, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "C:\Dev\xonsh\xonsh\built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "C:\Dev\xonsh\xonsh\environ.py", line 1272, in default_env
    issue_warning=False)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 502, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 241, in foreign_shell_data
    currenv = builtins.__xonsh_env__.detype()
AttributeError: 'dict' object has no attribute 'detype'

======================================================================
ERROR: test_imphooks.test_absolute_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_imphooks.py", line 34, in test_absolute_import
    from xpack import sample
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 79, in get_code
    execer = self.execer
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 30, in execer
    self._execer = execer = Execer(unload=False)
  File "C:\Dev\xonsh\xonsh\execer.py", line 44, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "C:\Dev\xonsh\xonsh\built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "C:\Dev\xonsh\xonsh\environ.py", line 1272, in default_env
    issue_warning=False)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 502, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 241, in foreign_shell_data
    currenv = builtins.__xonsh_env__.detype()
AttributeError: 'dict' object has no attribute 'detype'

======================================================================
ERROR: test_imphooks.test_relative_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_imphooks.py", line 39, in test_relative_import
    from xpack import relimp
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 79, in get_code
    execer = self.execer
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 30, in execer
    self._execer = execer = Execer(unload=False)
  File "C:\Dev\xonsh\xonsh\execer.py", line 44, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "C:\Dev\xonsh\xonsh\built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "C:\Dev\xonsh\xonsh\environ.py", line 1272, in default_env
    issue_warning=False)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 502, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 241, in foreign_shell_data
    currenv = builtins.__xonsh_env__.detype()
AttributeError: 'dict' object has no attribute 'detype'

======================================================================
ERROR: test_imphooks.test_sub_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Dev\xonsh\tests\test_imphooks.py", line 45, in test_sub_import
    from xpack.sub import sample
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 79, in get_code
    execer = self.execer
  File "C:\Dev\xonsh\xonsh\imphooks.py", line 30, in execer
    self._execer = execer = Execer(unload=False)
  File "C:\Dev\xonsh\xonsh\execer.py", line 44, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "C:\Dev\xonsh\xonsh\built_ins.py", line 699, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "C:\Dev\xonsh\xonsh\environ.py", line 1272, in default_env
    issue_warning=False)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 502, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Dev\xonsh\xonsh\foreign_shells.py", line 241, in foreign_shell_data
    currenv = builtins.__xonsh_env__.detype()
AttributeError: 'dict' object has no attribute 'detype'

----------------------------------------------------------------------
Ran 132596 tests in 17.342s

FAILED (SKIP=8, errors=8)
```

**Comment by melund** [comment]
https://github.com/scopatz/xonsh/pull/994 

Are there any improvements to the reliability of appveyor? Should we enable the windows tests again?

**Comment by scopatz** [comment]
I think that we should try re-enabling appveyor.  It would really help.  I'll try doing that now.

**Comment by scopatz** [comment]
Also, @mwiebe can you test and see if this works for you now?

**Comment by mwiebe** [comment]
Yes, that fixes it!

```
...
----------------------------------------------------------------------
Ran 132614 tests in 20.780s

OK (SKIP=7)
```

**Comment by scopatz** [comment]
Great!  Feel free to close this issue then :)

**Comment by scopatz** [comment]
@melund - appveyor continues to hate us for some reason. I re-disabled it.
